### PR TITLE
[test_this_on_travis] from #262

### PR DESCRIPTION
**Pull request by JunsubHan4rmEricsson**
Merged from #262 for travis regression test

### CODE REVIEW

**Comment by hhaim** [comment]
[test_this_on_travis]

**Comment by JunsubHan4rmEricsson** [comment]
> ⚠️
> Dear Junsub Han,
> You are trying to run tests on our servers with _run_this_on_travis_ keyword but you are not in our users whitelist.
> Only authorized users can to so, in order to be included please contact the repository admin

Hanoh, I'm trying to run the regression after some investigation.
Could you please allow me the regression to run?

**Comment by JunsubHan4rmEricsson** [comment]
> ⚠️
> Dear Junsub Han,
> You are trying to run tests on our servers with _run_this_on_travis_ keyword but you are not in our users whitelist.
> Only authorized users can to so, in order to be included please contact the repository admin

Could you please let the regression run?

**Comment by elados93** [comment]
@JunsubHan4rmEricsson  I added you as an authorized user, your tests are running right now and trex-bot wil send you the results when it's done.
Notice we committed some changes so make sure you sync with us later.

**Pull request closed without merging**
