### PR TITLE
ASTF profile parsing at CP core by user control

### PR DESCRIPTION
**Pull request by jsmoon**
Hi, this change is to implement the discussion result from #901.

I added `process_at_cp` in `global_cfg` for this feature activation to keep backward compatibility of profile scaling.

@hhaim, please review my changes and give your feedback.

### CODE REVIEW

**Comment by hhaim** [comment]
@jsmoon looks good

**Comment by jsmoon** [comment]
@hhaim when you can merge this PR? I have been waiting for 2 weeks now.

**Comment by hhaim** [comment]
@jsmoon sorry for the delay, I hope today. I've been on vacation

**Comment by hhaim** [comment]
rebased

**Pull request closed without merging**
