### PR TITLE
ASTF Dynamic Multiple Profile in Client side 

### PR DESCRIPTION
**Pull request by ejangle**
Hi,
@egwakim @ejaecki @Kangphil @yonghwan007 @jsmoon @JunsubHan4rmEricsson @youngjun1 @Cyborn-Minjae-Lee

I added client code for ASTF dynamic multiple profile. 
Major changes is as below.

1) Added "--pid" option/ dynamic_profile argument to APIs
   - "--pid profile_name(‘_’ is default, ‘*’ is all)" and “no option” means default ‘--pid “_”’
   - the changed APIs : 
     reset : added profiles clear/ stop : added "--remove" option/ profiles(new API)/ get_profiles(new API)
	 start/ load_profile/ stop/ clear/ clear_stats/ clear_traffic_stats/ update/ clear_profile
     stats/ get_stats/ template_group names/ get_tg_names/ template_group stats/ get_traffic_tg_stats
2) Added handling new event (60, 61)
   - EVENT_ASTF_PROFILE_STATE_CHG(60) -> Update profile state in astf_profile_state dictionary
   - EVENT_ASTF_PROFILE_CLEARED(61) -> Remove profile_id in astf_profile_state dictionary

### CODE REVIEW

**Comment by ejangle** [comment]
Hi
Today, I committed twice on the GitHub.
but the last("sha: df05cb8") is important. 
so I want to stop regression test for "sha: e1e9be8"
How can I stop this ?

**Comment by hhaim** [comment]
> Hi
> Today, I committed twice on the GitHub.
> but the last("sha: [df05cb8](https://github.com/cisco-system-traffic-generator/trex-core/commit/df05cb85c9ce09bfcf538fe4bbb86ca19ce75192)") is important.
> so I want to stop test for "sha: [e1e9be8](https://github.com/cisco-system-traffic-generator/trex-core/commit/e1e9be8448ade09d449d9726387b3ffcdb618a4f)"
> It is on the test now. How can I stop it 

You can go to Travis and cancel the build **but** under the hood the **resource** is already lost  

Suggest to test your code locally first. Our regression is expensive and should be used only when the local regression (at least with trex-08 setup) is not broken as a last resort

**Comment by jsmoon** [comment]
But my member including me can't see any cancel menu. We can only see
Requests menu.

2019년 5월 30일 (목) 오후 6:54, Hanoh Haim <notifications@github.com>님이 작성:

**Comment by hhaim** [comment]
Looks good. There is a arch question regarding the tcp_udp statistics. 
for now all the counters are per profile and as I said in prev PR 
there should be 1. global 2. per profile
let's talk about it in the next meeting

**Comment by ejangle** [comment]
I added new RPC command: "get_total_counter_values"
"stats -a" will display statistics of all profiles
Regression test in our environments were done.

**Comment by hhaim** [comment]
DP threads is there now. I will test this PR

**Comment by egwakim** [comment]
DP/CP merged now.
If you found any issue on this PR(Client), please add comment about it.
We'll send PR about 'regression test cases' after this client part merged.

BR
Gwangmoon

**Comment by hhaim** [comment]
The client code works fine. Will merge it today

**Comment by hhaim** [comment]
rebased

**Pull request closed without merging**
