### PR TITLE
pacakge -> package + make client infinitely wait (if timeout == -1)

### PR DESCRIPTION
**Pull request by zverevalexei**

### CODE REVIEW

**Comment by zverevalexei** [comment]
+ @hhaim

**Comment by zverevalexei** [comment]
More comments on that:

1. Commit 7b3a785 just fixes a typo

2. Commit a25c9b9 introduces a feature to keep connection alive infinitely when using stateless client

**Comment by zverevalexei** [comment]
@hhail I thought it was used to keep the connection alive besides stopping the traffic

**Comment by hhaim** [comment]
Just don't close the client object (disconnect API). after you start the traffic, you can call any API (get_stats usually )
or you can sleep

**Comment by zverevalexei** [comment]
Ok, I'll give it a try. 
Thanks!

**Pull request closed without merging**
