### PR TITLE
fix ASTF multi-profile is not stable of issue #360

### PR DESCRIPTION
**Pull request by jsmoon**
This PR is related to #360.
This change is for the ASTF issue only.
I've found my last suggestion was not enough to solve this. It needed more change to update the ASTF state properly.
I hope this change may solve the ASTF issue.

### CODE REVIEW

**Comment by hhaim** [comment]
@jsmoon I took the most problematic setup and run those tests in loop without success to reproduce it (before your commit)
I will merge this and re-enable the test (astf) for now

**Comment by hhaim** [comment]
image

Almost all the setup failed with this commit. I will remove the test again

**Comment by hhaim** [comment]
the server crash (I'm not sure it related to the fix your sent)

image

**Comment by jsmoon** [comment]
I think it came from my change.
m_error should not be accessed after removed.
I'll fix it by tomorrow.

**Comment by hhaim** [comment]
yes, It point to your commit. I've revert it and disable the tests again.

**Comment by jsmoon** [comment]
@hhaim The last FAILURE occurred at the STL performance test. It doesn't seem like originated my code change.
Anyway, I found a possible hanging issue in the ASTFClient stop. My last commit will remove the possibility.

**Comment by hhaim** [comment]
@jsmoon it does not seem to solve the issue. The test failed

**Comment by hhaim** [comment]
@jsmoon BTW it is something new, I need to track the failures to specific commit

**Comment by hhaim** [comment]
@jsmoon isn't it related to the same transient state solved in 
https://github.com/cisco-system-traffic-generator/trex-core/pull/359
Does it make sense to solve both issues in one PR?

**Comment by jsmoon** [comment]
> isn't it related to the same transient state solved in
> #359 

What does `it` mean?
I think the test FAILURE reason is related to issue #360 and #361.
So, this PR can make the PR #359 test passed.

> Does it make sense to solve both issues in one PR?

If the reason is the same, I think it makes sense.

**Comment by hhaim** [comment]
From Elastic Search analysis it point to this commit 

https://github.com/cisco-system-traffic-generator/trex-core/commit/f56ee31d41a9a306789334f0e3e7b0799bb56eed

I've created a new branch (with this commit blackout) to verify it, will let you know.

**Comment by hhaim** [comment]
@jsmoon Ok, I've ran it a few times and it seems more stable (with Reset commit)
I will merge it.

**Pull request closed without merging**
