### PR TITLE
Add base support for bnxt PMD from dpdk 19.05

### PR DESCRIPTION
**Pull request by gospo**
Signed-off-by: Don Wallwork <don.wallwork@broadcom.com>
Signed-off-by: Andy Gospodarek <gospo@broadcom.com>

### CODE REVIEW

**Comment by gospo** [comment]
Third time's the charm????

**Comment by gospo** [comment]
Any reason why the automated testing tools have not been kicked off for this pull request?

**Comment by hhaim** [comment]
@gospo One comment, looking into the trex driver I see that you added support only the basic capabilities of the NIC. For example, you didn't add hardware filters for STL mode or low latency HW filters for ASTF.

**Comment by hhaim** [comment]
rebased

**Comment by gospo** [comment]
@hhaim Yes, we knew we were missing some of the features that will make trex more performant -- we plan to add them soon, but needed to get an initial commit in place for buy-in.  Thanks!

**Pull request closed without merging**
