### PR TITLE
prevent surplus packets from ARP on STLFlowLatencyStats

### PR DESCRIPTION
**Pull request by jsmoon**
Hi, this PR is the change for the reverted PR #659.

In this change, only the broadcast mac address will be excluded using by `isDefaultAddress()` method.
I rewrote the `RXLatency::handle_pkt()` also.

@hhaim please check my code and give your feedback.

### CODE REVIEW

**Comment by hhaim** [comment]
see minor changes here
https://github.com/hhaim/trex-core/tree/bidtt4-update_RXLatency_handle_pkt

**Comment by jsmoon** [comment]
@hhaim, better than my code.

**Comment by hhaim** [comment]
rebased with minor changes

**Comment by jsmoon** [comment]
@hhaim I'm sorry I missed one point. your change may not cover the following case.

<non-IP packet> --> DUT --> <IP packet>

In this case, the flow latency packet will not be detected properly.

**Comment by hhaim** [comment]
@jsmoon who said that we need to support it? The original design supported **only** valid IP with ip.id. 
Then we added non-ip with meta-data only in **software mode**. The fact that the old code supported very strange options is not an indication that this is what we wanted to support.

**Comment by jsmoon** [comment]
@hhaim, actually my user uses it. My company's custom packet is translated to the IP packet and vice versa.
So I added to check the latency magic first in software mode regardless of ip.id.

**Comment by hhaim** [comment]
@jsmoon what if the ip.id in your case? it is a valid ip.id or not?

**Comment by jsmoon** [comment]
@hhaim it's random. some packets have valid ip.id and some packets haven't.

**Comment by hhaim** [comment]
@jsmoon it means that there should be a better way to identify that this packet is a latency packet. 
MAGIC of one byte (0xAB) is lame ..
better to change the header  magic and the validation in this case

**Comment by jsmoon** [comment]
@hhaim I agree. what about adding a additional field to confirm the MAGIC byte is valid?
I think the last byte can has the checksum or another MAGIC field.
What do you think about it?

**Comment by hhaim** [comment]
I would create another verification function that will have more strength (only on software mode) but keep the same size. 

1. check magic 
2. check that time_stamp is reasonable (diff is less than +-2 sec)
3. hw_id is in range
4. seq is in range (MAXIMUM DROP +=1000) 

```
    uint8_t magic;
    uint8_t flow_seq;
    uint16_t hw_id;
    uint32_t seq;
    uint64_t time_stamp;
```

**Comment by jsmoon** [comment]
@hhaim 1. and 3. are already checked currently.
for 2. and 4. I'm not sure how to handle the first packet when there is no previous packet.
I would make the decision by the packet itself.
time_stamp could be compared with *the current time* for checking the packet is a valid latency packet.

**Comment by egwakim** [comment]
Hi @hhaim
The balanced way(performance vs strong checking) would be checking existing fields as you suggested.
(Keep 16 bytes header for the cache and pipeline)
Checking existing 64 bits time_stamp(Valid if now()-5sec ~ now()+5sec) seems lightweight and strong enough to check the validity.

Limiting flow_latency feature to IP packet only is not an good idea, many users have been used flow_latency stats because of the custom packet feature. Since flow_latency add own custom header, it can distinguish flows whatever header(IP or non-IP) changed or not. It's very useful feature.

**Comment by hhaim** [comment]
@egwakim agreed. Adding time_stamp ~4sec validation will add 32bit header comparison which is stronger than  ip.id (16 bit). 
I suggest to **add** this validation only in **software** mode.

**Pull request closed without merging**
