### PR TITLE
Fix memory leak and invalid access

### PR DESCRIPTION
**Pull request by jsmoon**
Hi, this PR is to fix some memory leak possibilities and invalid access which are reported by `cppcheck`.

```
src/44bsd/tcp_socket.h:127: error: Invalid number of character '{' when these macros are defined: 'FIXME'.
src/44bsd/tcp_input.cpp:664: error: Uninitialized variable: ts_val
src/44bsd/tcp_input.cpp:688: error: Uninitialized variable: ts_ecr
src/astf/astf_db.cpp:1147: error: Memory leak: ret
src/astf/astf_db.cpp:1244: error: Memory leak: temp_rw
src/sim/trex_sim_stateful.cpp:585: error: Array 'merger.m[2]' accessed at index 2, which is out of bounds.
src/utils/utl_port_map.cpp:160: error: Memory leak: lp
```
I don't fix the errors in `src/44bsd/tcp_input.cpp` because they have no issue.

@hhaim please check my changes and give your feedback

### CODE REVIEW

**Comment by jsmoon** [comment]
@hhaim could you check this trex-bot failure reason?

**Comment by bdollma** [comment]
```
Python3 test
Traceback (most recent call last):
  File "trex_unit_test.py", line 753, in <module>
    result = nose.run(argv = nose_argv + additional_args, addplugins = addplugins) and result
  File "/tmp/jenkins/unzipped/external_libs/nose-1.3.4/python3/nose/core.py", line 301, in run
    return TestProgram(*arg, **kw).success
  File "/tmp/jenkins/unzipped/external_libs/nose-1.3.4/python3/nose/core.py", line 121, in __init__
    **extra_args)
  File "/usr/lib64/python3.6/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/tmp/jenkins/unzipped/external_libs/nose-1.3.4/python3/nose/core.py", line 145, in parseArgs
    self.config.configure(argv, doc=self.usage())
  File "/tmp/jenkins/unzipped/external_libs/nose-1.3.4/python3/nose/config.py", line 346, in configure
    self.plugins.configure(options, self)
  File "/tmp/jenkins/unzipped/external_libs/nose-1.3.4/python3/nose/plugins/manager.py", line 284, in configure
    cfg(options, config)
  File "/tmp/jenkins/unzipped/external_libs/nose-1.3.4/python3/nose/plugins/manager.py", line 99, in __call__
    return self.call(*arg, **kw)
  File "/tmp/jenkins/unzipped/external_libs/nose-1.3.4/python3/nose/plugins/manager.py", line 167, in simple
    result = meth(*arg, **kw)
  File "trex_unit_test.py", line 399, in configure
    if not CTRexScenario.trex.check_master_connectivity():
  File "/tmp/jenkins/unzipped/automation/trex_control_plane/stf/trex_stf_lib/trex_client.py", line 1057, in check_master_connectivity
    return self.master_daemon.check_connectivity()
  File "/tmp/jenkins/unzipped/external_libs/jsonrpclib-pelix-0.4.1/jsonrpclib/jsonrpc.py", line 764, in __call__
    return self.__send(self.__name, kwargs)
  File "/tmp/jenkins/unzipped/external_libs/jsonrpclib-pelix-0.4.1/jsonrpclib/jsonrpc.py", line 643, in _request
    response = self._run_request(request)
  File "/tmp/jenkins/unzipped/external_libs/jsonrpclib-pelix-0.4.1/jsonrpclib/jsonrpc.py", line 676, in _run_request
    verbose=self.__verbose
  File "/usr/lib64/python3.6/xmlrpc/client.py", line 1154, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/tmp/jenkins/unzipped/external_libs/jsonrpclib-pelix-0.4.1/jsonrpclib/jsonrpc.py", line 377, in single_request
    response = connection.getresponse()
  File "/usr/lib64/python3.6/http/client.py", line 1346, in getresponse
    response.begin()
  File "/usr/lib64/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.6/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib64/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out
```

Seems like a timeout. Need to resend.

**Comment by bdollma** [comment]
recheck

**Comment by hhaim** [comment]
rebased

**Pull request closed without merging**
