### PR TITLE
Added a new test ASTF regression test cases for dynamic profile feature

### PR DESCRIPTION
**Pull request by JunsubHan4rmEricsson**
@hhaim 
This is derived from #300 and #299 
I have fixed the problems you've mentioned

### CODE REVIEW

**Comment by hhaim** [comment]
I still see that you override the master code 
Could you say why?

```
@try_few_times
    def run_astf_profile(self, profile_name, m, is_udp, is_tcp, ipv6 =False, check_counters=True, nc = False, short_duration = False):
    def run_astf_profile(self, profile_name, m, is_udp, is_tcp, ipv6 =False, check_counters=True, nc = False):
        c = self.astf_trex;


```

**Comment by JunsubHan4rmEricsson** [comment]
> I still see that you override the master code
> Could you say why?
> 
> ```
> @try_few_times
>     def run_astf_profile(self, profile_name, m, is_udp, is_tcp, ipv6 =False, check_counters=True, nc = False, short_duration = False):
>     def run_astf_profile(self, profile_name, m, is_udp, is_tcp, ipv6 =False, check_counters=True, nc = False):
>         c = self.astf_trex;
> ```

I think I accidentally removed while I was fixing the merge conflicts.
I rolled it back.

**Comment by JunsubHan4rmEricsson** [comment]
Could you please check the last commit and allow the PR?

**Comment by hhaim** [comment]
I still see issues, see this function
```
def test_stress_start_stop_dynamic_profile(self):
```

My branch with the fixes is not working yet. Let me fix it and then add your fixes on top of that

**Comment by JunsubHan4rmEricsson** [comment]
> I still see issues, see this function
> 
> ```
> def test_stress_start_stop_dynamic_profile(self):
> ```
> 
> My branch with the fixes is not working yet. Let me fix it and then add your fixes on top of that

What's the issue with the test case. It seems that the regression has just passed

**Comment by JunsubHan4rmEricsson** [comment]
And you didn't mention "test_stress_start_stop_dynamic_profile" having any issues before.
Could you please list up all the issues so I can solve them all ?
It's confusing because regression keeps passing.

**Comment by hhaim** [comment]
DMZ has only one setup (similar to trex-08) while our internal regression has many types of setups most of them crashed due to our of memory. 

Please take my full branch and inspect it, start with this function

**Comment by JunsubHan4rmEricsson** [comment]
1. Is "test_stress_start_stop_dynamic_profile" the only one with issues?
2. What's your full branch? Where can I get it?

**Comment by hhaim** [comment]
see my comments here 
https://github.com/cisco-system-traffic-generator/trex-core/pull/300

**Comment by hhaim** [comment]
```
```
astf_tests.astf_resilience_test.ASTFResilience_Test.test_double_start_stop (from nosetests)

Failing for the past 1 build (Since Failed#311162 )
Took 6 ms.
add description
Error Message
'eochihmadf'
Stacktrace
Traceback (most recent call last):
  File "/usr/lib64/python3.4/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib64/python3.4/unittest/case.py", line 614, in run
    self.setUp()
  File "/tmp/trex-scripts/automation/regression/astf_tests/astf_resilience_test.py", line 14, in setUp
    CASTFGeneral_Test.setUp(self)
  File "/tmp/trex-scripts/automation/regression/astf_tests/astf_general_test.py", line 24, in setUp
    self.astf_trex.reset()
  File "/tmp/trex-scripts/automation/trex_control_plane/interactive/trex/common/trex_api_annotators.py", line 51, in wrap2
    ret = f(*args, **kwargs)
  File "/tmp/trex-scripts/automation/trex_control_plane/interactive/trex/astf/trex_astf_client.py", line 344, in reset
    self.stop(pid_input = ALL_PROFILE_ID)
  File "/tmp/trex-scripts/automation/trex_control_plane/interactive/trex/common/trex_api_annotators.py", line 51, in wrap2
    ret = f(*args, **kwargs)
  File "/tmp/trex-scripts/automation/trex_control_plane/interactive/trex/astf/trex_astf_client.py", line 649, in stop
    rc = self._transmit_async('stop', params = params, ok_states = [self.STATE_IDLE, self.STATE_ASTF_LOADED])
  File "/tmp/trex-scripts/automation/trex_control_plane/interactive/trex/astf/trex_astf_client.py", line 292, in _transmit_async
    self.wait_for_steady(profile_id)
  File "/tmp/trex-scripts/automation/trex_control_plane/interactive/trex/astf/trex_astf_client.py", line 274, in wait_for_steady
    state = self.astf_profile_state[pid_input] if self.is_dynamic else self.state
KeyError: 'eochihmadf'

````

This is another failure

**Comment by hhaim** [comment]
Another issue

Setup	Failed tests:	Final Result	Time (s)
trex22	astf_tests.astf_template_group_test.ASTFTemplateGroup_Test.test_astf_template_group_negative_dynamic_profile	ERROR	0.400
Error:
Traceback (most recent call last):
File "/usr/lib64/python3.4/unittest/case.py", line 59, in testPartExecutor
yield
File "/usr/lib64/python3.4/unittest/case.py", line 618, in run
testMethod()
File "/tmp/trex-scripts/automation/regression/astf_tests/astf_template_group_test.py", line 461, in test_astf_template_group_negative_dynamic_profile
self.c.clear_stats(pid_input=str(random_profile))
File "/tmp/trex-scripts/automation/trex_control_plane/interactive/trex/common/trex_api_annotators.py", line 51, in wrap2
ret = f(*args, **kwargs)
File "/tmp/trex-scripts/automation/trex_control_plane/interactive/trex/astf/trex_astf_client.py", line 781, in clear_stats
valid_pids = self.validate_profile_id_input(pid_input)
File "/tmp/trex-scripts/automation/trex_control_plane/interactive/trex/astf/trex_astf_client.py", line 239, in validate_profile_id_input
raise TRexError("ASTF profile_id %s does not exist." % profile_id)
trex.common.trex_exceptions.TRexError: ASTF profile_id ywrrzkzmff does not exist.


Stdout:
Creating random name for the dynamic profile
Dynamic profile name : ywrrzkzmff

>>>>>>>>>>>>>>> Daemon log <<<<<<<<<<<<<<<
07-15 16:51:03 trex_server INFO Processing get_trex_log() command.
07-15 16:51:04 trex_server INFO Processing get_trex_daemon_log() command.

>>>>>>>>>>>>>>>> Trex log <<<<<<<<<<<<<<<<
The ports are bound/configured.
Starting TRex v2.59 please wait ... 
set driver name net_i40e_vf 
driver capability : TCP_UDP_OFFLOAD TSO 
set dpdk queues mode to ONE_QUE 
Number of ports found: 4
zmq publisher at: tcp://*:4500
wait 5 sec .....

**Comment by JunsubHan4rmEricsson** [comment]
> Another issue
> 
> Setup	Failed tests:	Final Result	Time (s)
> trex22	astf_tests.astf_template_group_test.ASTFTemplateGroup_Test.test_astf_template_group_negative_dynamic_profile	ERROR	0.400
> Error:
> Traceback (most recent call last):
> File "/usr/lib64/python3.4/unittest/case.py", line 59, in testPartExecutor
> yield
> File "/usr/lib64/python3.4/unittest/case.py", line 618, in run
> testMethod()
> File "/tmp/trex-scripts/automation/regression/astf_tests/astf_template_group_test.py", line 461, in test_astf_template_group_negative_dynamic_profile
> self.c.clear_stats(pid_input=str(random_profile))
> File "/tmp/trex-scripts/automation/trex_control_plane/interactive/trex/common/trex_api_annotators.py", line 51, in wrap2
> ret = f(*args, **kwargs)
> File "/tmp/trex-scripts/automation/trex_control_plane/interactive/trex/astf/trex_astf_client.py", line 781, in clear_stats
> valid_pids = self.validate_profile_id_input(pid_input)
> File "/tmp/trex-scripts/automation/trex_control_plane/interactive/trex/astf/trex_astf_client.py", line 239, in validate_profile_id_input
> raise TRexError("ASTF profile_id %s does not exist." % profile_id)
> trex.common.trex_exceptions.TRexError: ASTF profile_id ywrrzkzmff does not exist.
> 
> Stdout:
> Creating random name for the dynamic profile
> Dynamic profile name : ywrrzkzmff
> 
> > > > > > > > > > > > > > > > Daemon log <<<<<<<<<<<<<<<
> > > > > > > > > > > > > > > > 07-15 16:51:03 trex_server INFO Processing get_trex_log() command.
> > > > > > > > > > > > > > > > 07-15 16:51:04 trex_server INFO Processing get_trex_daemon_log() command.
> 
> > > > > > > > > > > > > > > > > Trex log <<<<<<<<<<<<<<<<
> > > > > > > > > > > > > > > > > The ports are bound/configured.
> > > > > > > > > > > > > > > > > Starting TRex v2.59 please wait ...
> > > > > > > > > > > > > > > > > set driver name net_i40e_vf
> > > > > > > > > > > > > > > > > driver capability : TCP_UDP_OFFLOAD TSO
> > > > > > > > > > > > > > > > > set dpdk queues mode to ONE_QUE
> > > > > > > > > > > > > > > > > Number of ports found: 4
> > > > > > > > > > > > > > > > > zmq publisher at: tcp://*:4500
> > > > > > > > > > > > > > > > > wait 5 sec .....

Does this error still take place after the last commit? **cd91f9a**
The line of script "self.c.clear_stats(pid_input=str(random_profile))" does not exit anymore.
Could you please update me with the **latest** regression that's run?
It's very confusing

**Comment by JunsubHan4rmEricsson** [comment]
Since your comment, 
"The tests look good. The time is reasonable now.
Will try to merge to master."
These are the issues that have taken place. 

Issue #1. test_astf_template_group_edge_cases_dynamic_profile 
-> Fixed in the previous commit, "82ec8f4" (https://github.com/cisco-system-traffic-generator/trex-core/pull/300/commits/82ec8f4256a734ce6f04fdab2380bf1766776857)
-> Could you please check if the same error still takes place with the commit, "82ec8f4"

Issue #2. run_astf_profile
-> Rolled back with the commit, "cd91f9a" (https://github.com/cisco-system-traffic-generator/trex-core/pull/304/commits/cd91f9a4b90035e1c68804b51643c7aed8ca17a4)

Issue #3. test_stress_start_stop_dynamic_profile
-> Not mentioned in #300 (https://github.com/cisco-system-traffic-generator/trex-core/pull/300)
-> You did mention another test case "test_astf_template_group_edge_cases_dynamic_profile" in #300. I have fixed it as mentioned in "Issue #1".
-> However, I made it so that this test case can be skipped if self.weak

Issue #4. test_double_start_stop
-> Does this error still take place?
-> Will check with the client side designer

Issue #5. test_astf_template_group_negative_dynamic_profile	
-> Fixed in the previous commit, "82ec8f4" (https://github.com/cisco-system-traffic-generator/trex-core/pull/300/commits/82ec8f4256a734ce6f04fdab2380bf1766776857)
-> Could you please check if the same error still takes place with the commit, "82ec8f4"

**Comment by hhaim** [comment]
I'm sorry for the confusion, (I'm out of the office this week).
This is the last commit (there is a typo :: -> :)

branch:
https://github.com/hhaim/trex-core/commits/astf_regression1

last commit:
https://github.com/hhaim/trex-core/commit/3047e6105b4dcea420cb257cbae65cfe11f27bad
Typo to fix
```
        if setup in ['trex41']::
            self.low_memory = True # trex-41 uses the memory for the driver and crash
```

So This is what I suggest. Take this branch as a base and add your fixes on top of that and I will re-run it against all the setups

This branch has 2 test masked ( need to re-enabled them) and still has one failure  (trex-22)

**Comment by JunsubHan4rmEricsson** [comment]
@hhaim 
I've adopted the change you have made in https://github.com/hhaim/trex-core/commit/3047e6105b4dcea420cb257cbae65cfe11f27bad

And I've also unmasked two test cases "test_astf_params_dynamic_profile" and "test_astf_template_group_edge_cases_dynamic_profile"

Please check the commit, https://github.com/cisco-system-traffic-generator/trex-core/pull/304/commits/547c7edc1e37a42906313461258c8116be2410bf

**Comment by hhaim** [comment]
It is not just one fix that I did. Please take my branch as the baseline and add your changes.
I did many changes in different places

**Comment by JunsubHan4rmEricsson** [comment]
@hhaim 
I've merged all of your changes into mine.
Please check: 
https://github.com/cisco-system-traffic-generator/trex-core/pull/304/commits/9a3be8e9945bb52b890dbf1ee79888c784af6126
https://github.com/cisco-system-traffic-generator/trex-core/pull/304/commits/3c47977e352a11c4f595adae963fd8492ff5dae4
https://github.com/cisco-system-traffic-generator/trex-core/pull/304/commits/760b0b548b252e41acd9cb991cee022d55a7aabf

**Comment by hhaim** [comment]
@JunsubHan4rmEricsson why have you removed the tests.
I would like to keep them and understand the root cause of the failures (it happens on our local regression too)

**Comment by JunsubHan4rmEricsson** [comment]
> @JunsubHan4rmEricsson why have you removed the tests.
> I would like to keep them and understand the root cause of the failures (it happens on our local regression too)

1. I've rolled back the tests as you suggested. 
2. I found the errors that caused 760b0b5 to fail. I have fixed them with 83dfa3f
However, I'm not sure why functional test fails for 83dfa3f. 
It passes just fine our environment

**Comment by hhaim** [comment]
Please revert the removal of the tests and try to understand the failures

**Comment by JunsubHan4rmEricsson** [comment]
> Please revert the removal of the tests and try to understand the failures

Yes I've done that.
One of the reasons why the test failed previously was because astf_profile_state has been accessed through
**astf_profile_state[profile_id]**
instead of 
**astf_profile_state.get(profile_id)**
Therefore, the test failed in case the profile_id does not exist

**Comment by hhaim** [comment]
Understood. I will run it

**Comment by JunsubHan4rmEricsson** [comment]
@hhaim did it work?

**Comment by hhaim** [comment]
Hi @JunsubHan4rmEricsson 
There is a progress, the old issues are gone but there is a new one
 
I got this error  (Every run on a different setup)

It starts after this test.
```test_random_add_remove_dynamic_profile (astf_tests.astf_profile_test.ASTFProfile_Test) ... ERROR```

```
DP core should not report error in state: Transmitting
Error is: Start in unexpected DP core state: 3

```

try to run a loop on those tests (until this test) to find the culprit 

image

**Comment by JunsubHan4rmEricsson** [comment]
> test_random_add_remove_dynamic_profile

Could you please send me the entire log?
Does any other test cause error besides **"test_random_add_remove_dynamic_profile"**

**Comment by hhaim** [comment]
Unfortunately, this is the entire log. Once the server is down all the tests fail

**Comment by JunsubHan4rmEricsson** [comment]
I will share this issue with my colleagues. 
@Cyborn-Minjae-Lee @egwakim @ejangle @JaeyongYu @jsmoon @JunsubHan4rmEricsson @taewoonyun @yonghwan007 @youngjun1

**Comment by hhaim** [comment]
Any update with this issue? do you want to mark this test for now?

**Comment by JunsubHan4rmEricsson** [comment]
@youngjun1 
I have created an internal task to be worked on.
But for now, we're occupied with other tasks. 
I will talk to my scrum master about this issue again.
Thanks.

**Comment by egwakim** [comment]
Hi Hanoh,
Regarding 'test_random_add_remove_dynamic_profile' issue,
I think we need to separate this issue with regression test.
Proposed way is
1. Create related issue ticket about it(test_random_add_remove_dynamic_profile) and follow it
2. Remove related test case(test_random_add_remove_dynamic_profile) until above issue resolved.

How about your opinion?

Best Regards
Gwangmoon

**Comment by hhaim** [comment]
@egwakim 
We can do that. However, we should solve the issue.

**Comment by egwakim** [comment]
Ok,
I created related issue here(https://github.com/cisco-system-traffic-generator/trex-core/issues/324)
It need to be fixed.

**Comment by JunsubHan4rmEricsson** [comment]
@hhaim will it be possible to merge the regression tests without "test_random_add_remove_dynamic_profile" which is caused by the problem in the dp?

**Comment by hhaim** [comment]
Yes, the internal regression is running right now to verify if there is no other issues.

**Comment by JunsubHan4rmEricsson** [comment]
@hhaim Let me know how the test result turns out

**Comment by hhaim** [comment]
It is still not stable with this test:

astf_tests.astf_resilience_test.ASTFResilience_Test.test_double_start_stop

ex.common.trex_exceptions.TRexError: ASTF profile_id ydssgaudyo does not exist

**Comment by JunsubHan4rmEricsson** [comment]
Can you show me the log?

**Comment by hhaim** [comment]
1. There is no more logs than that 
2. No, it is the **main** one
3. On all the setup. It happen ~1/30 times

running the regression in loop on your setup would reconstruct it

**Comment by JunsubHan4rmEricsson** [comment]
Logs like this 

> Setup	Failed tests:	Final Result	Time (s)
> trex22 astf_tests.astf_template_group_test.ASTFTemplateGroup_Test.test_astf_template_group_negative_dynamic_profile	ERROR	0.400
> Error:
> Traceback (most recent call last):
> File "/usr/lib64/python3.4/unittest/case.py", line 59, in testPartExecutor
> yield
> File "/usr/lib64/python3.4/unittest/case.py", line 618, in run
> testMethod()
> File "/tmp/trex-scripts/automation/regression/astf_tests/astf_template_group_test.py", line 461, in test_astf_template_group_negative_dynamic_profile
> self.c.clear_stats(pid_input=str(random_profile))
> File "/tmp/trex-scripts/automation/trex_control_plane/interactive/trex/common/trex_api_annotators.py", line 51, in wrap2
> ret = f(*args, **kwargs)
> File "/tmp/trex-scripts/automation/trex_control_plane/interactive/trex/astf/trex_astf_client.py", line 781, in clear_stats
> valid_pids = self.validate_profile_id_input(pid_input)
> File "/tmp/trex-scripts/automation/trex_control_plane/interactive/trex/astf/trex_astf_client.py", line 239, in validate_profile_id_input
> raise TRexError("ASTF profile_id %s does not exist." % profile_id)
> trex.common.trex_exceptions.TRexError: ASTF profile_id ywrrzkzmff does not exist.

So I can see in which function the error has taken place

**Comment by hhaim** [comment]
65FE6FDD-7F6F-469C-A93F-CF09C9348BF3

**Comment by JunsubHan4rmEricsson** [comment]
@ejangle @egwakim 
Even though in the test case, **test_astf_params_dynamic_profile** I reset the the profiles
the profile_id used is still left over in the next test case, **test_double_start_stop**. 

This profile_id is only left in the client side (not in server side).
That's why the error is taking place. 

I think this sync issue between client and server needs to be fixed as well...

**Comment by JunsubHan4rmEricsson** [comment]
@hhaim 
I've applied the changes to fix the sync issue during clear_profile.
Could you please tell me how the regression turned out?

**Comment by hhaim** [comment]
I’m out of office this week. The results might be delayed

**Comment by JunsubHan4rmEricsson** [comment]
Hi @hhaim 
When will I be notified with the test results?

**Comment by hhaim** [comment]
@JunsubHan4rmEricsson I didn’t forget. I OOO will do first thing on Sunday

**Comment by hhaim** [comment]
@JunsubHan4rmEricsson the regression is running now.

**Comment by hhaim** [comment]
image


Another crash in ASTF. I don't see this issue in the main branch (Elastic Search) so it might be related to the new tests (start_stop_dynamic_profile). 
Is  it related to issue #324
```
 -------------------------------
RX core uses TX queue number 2 on all ports
 core, c-port, c-queue, s-port, s-queue, lat-queue
 ------------------------------------------
 1        0      0       1       0      0  
 2        2      0       3       0      0  
 -------------------------------
eth_ntacc_rx_ext_buffer_release: Out of order release detected while running ext buffer mode.
./t-rex-64: line 80: 11115 Aborted                 (core dumped) ./_$(basename $0) $INPUT_ARGS $EXTRA_INPUT_ARGS



```

**Comment by JunsubHan4rmEricsson** [comment]
> I'm sorry for the confusion, (I'm out of the office this week).
> This is the last commit (there is a typo :: -> :)
> 
> branch:
> https://github.com/hhaim/trex-core/commits/astf_regression1
> 
> last commit:
> [hhaim@3047e61](https://github.com/hhaim/trex-core/commit/3047e6105b4dcea420cb257cbae65cfe11f27bad)
> Typo to fix
> 
> ```
>         if setup in ['trex41']::
>             self.low_memory = True # trex-41 uses the memory for the driver and crash
> ```
> 
> So This is what I suggest. Take this branch as a base and add your fixes on top of that and I will re-run it against all the setups
> 
> This branch has 2 test masked ( need to re-enabled them) and still has one failure (trex-22)

From what I remember, **stress_start_stop_dynamic_profile** has been an issue before but we fixed it.
Can I please look at the error in detail with your logs?

**Comment by JunsubHan4rmEricsson** [comment]
>     def test_stress_start_stop_dynamic_profile(self):
>         print('')
>         c = self.astf_trex
> 
>         profiles =1000
>         if self.low_memory:
>             profiles = 100

Above changes have been implemented as well.
And from what I understand this test case has been passing on your side

**Comment by JunsubHan4rmEricsson** [comment]
1. Has there been an error in **test_double_start_stop** in any cases?
2. Can I get the full log for the error which has taken place in **test_stress_start_stop_dynamic_profile**?
3. How many times does **test_stress_start_stop_dynamic_profile** fail?

**Comment by hhaim** [comment]
@JunsubHan4rmEricsson you are right, I forgot that I did it..
trex-41 has a memory limitation and I've reduced the amount of memory for this setup. 
The new patch fixed the the old sync error between the Client<->CP  

**see answers**:

1. no
2. there was one crash in trex-41 in ASTF due to memory 
4. the regression run 4 times only trex-41 fails due to crash before the test_stress_start_stop_dynamic_profile

I will let it run more to see if trex-41 is more sensitive maybe we need to to skip those test in this setup

**Comment by JunsubHan4rmEricsson** [comment]
Thanks.
Could you please check it and let me know?

**Comment by hhaim** [comment]
@JunsubHan4rmEricsson 
I ran 5 time the regression and it pass. will merge it

**Comment by hhaim** [comment]
@JunsubHan4rmEricsson Could you create a clean rebased branch on top of the latest? I can do this using rebase but then it won't have your name on it.

**Comment by JunsubHan4rmEricsson** [comment]
@hhaim 
I have created a new PR #329 
Please accept the pull request
Thanks.

**Comment by hhaim** [comment]
Obsolete

**Pull request closed without merging**
