### PR TITLE
Provide an API and infrastructure to toggle the state of a client

### PR DESCRIPTION
**Pull request by vineetbvp**
There will be 2 state:
1. Active: These clients will be sending traffic
2. Inactive: These clients wont be sending any traffic
By defaults all clients will be in active state

### CODE REVIEW

**Comment by hhaim** [comment]
@vineetbvp looks good in general a few notes. 

1)  >>>   if (m_active_clients.size() > 0 ) { this is always >0 as we try to disable at least one enabled client 
         
```
...
        m_ip_info[i]->set_is_active(activate);
        if (m_active_clients.size() > 0 ) {  >>> this is always >0 as we try to disable at least one enabled client 
           if (*m_cur_act_itr == i){
                m_cur_act_itr++;
           }
           auto it = m_ip_info[i]->get_ptr_to_active_list();
           if (it != m_active_clients.end()){
              m_active_clients.erase(it);
              m_ip_info[i]->set_ptr_to_active_list(m_active_clients.end());
           }
        }
```

2. I would prefer the to use ```TCDListNode``` instead of ```std::stl<list>``` that has another indirection 
Have a look into example (hash the uses it).  

3. Need to add a few query RPC (as oppose to RPC to enable/disable) 
3.1 the clients ranges 
3.2 per given list of clients, return a list of values (dict)
 *  client-exists 
 *  client- state (enable/disable) 
 *  more e.g. info tunnel info 

This way there could be a way to the python API to get all the client information back

**Comment by vineetbvp** [comment]
Response for comments:
1. Changed implementation . NA
2. Used TCDListNode instead of STL
3. Added RPC for query
    1. Currently it will provide state of client and if client present
     2. Will be extended in further commit

**Comment by hhaim** [comment]
@vineetbvp are you looking into the failure?

**Comment by vineetbvp** [comment]
I just briefly saw where it was failing. Then did not get time to look into it yet.

**Comment by hhaim** [comment]
Hi @vineetbvp 
Almost there,a few minor comments 
1. 
The following lines (with the same comments) repeat twice in the code, please consolidate it to one function in the ```CClientPool``` object 
```
        /*
          1. Associate this pool with client object. Store in m_ref_pool_ptr
          2. Create a DLL node , store this node in m_active_c_node list and then put into active client list of the pool
          3. Mark it active so that traffic can flow
        */
        m_ip_info[i]->add_ref_pool_ptr(this);
        ActiveClientListNode *cn = m_ip_info[i]->add_client_list_node(m_ip_info[i]);
        set_client_active(m_ip_info[i], cn, true);
```

or it is better to consolidate ```CClientPool::allocate_simple_clients```  and ```CClientPool::allocate_configured_clients``` functions to one (as there is a duplication, including your function)

2. 

```TrexRpcCmdEnableDisableClient::_run(const Json::Value &params, Json::Value &result) {```


In case of range, you are building a vector and send it to all cores, this make sense in case of a random list, but in case of range just send the range 
```
        for (uint32_t client_ip = client_start_ip; client_ip <= client_end_ip; client_ip++)
            msg_data.push_back(client_ip);
```

3. 
TrexRpcCmdGetClientsInfo::_run(const Json::Value &params, Json::Value &result) {

```
        for (uint32_t client_ip = client_start_ip; client_ip <= client_end_ip; client_ip++){
            for (int thread_id = 0; thread_id < cpu_util_full.size(); thread_id++) {

                CTupleGeneratorSmart* ctg = astf_db->get_smart_gen(thread_id);
                CFlowGenListPerThread *m_thread_ptr = ctg->get_client_flow_gen_list();
            
                CIpInfoBase *ip_info = m_thread_ptr->client_lookup(client_ip);  <<<<<<<<<<<<<<<< you can't do this!!!
                res[to_string(client_ip)] = client_data_to_json(ip_info);

                if (ip_info) /* Found no need to look in other thread */
                   break;
            } 
        }
```

You can't manipulate and call function of each core object. It can be accessed only by the DP core else there would be a race.  better to send a DP message to each core and wait for a response and merge all the responses. 

4. better to have a version of the API and a better doc 

enable_clients(self, client_list, is_enable):
enable_clients(self, client_start, client_end,is_enable):


```
    # execute 'method' for Making  a client active/inactive
    def enable_disable_client(self, client_list, is_enable, is_range):
        ''' 
        API to toggle state of client
        Input: List of client or list of client range and Action : state flag
        '''

        json_attr = []
        if is_range is False:
            for key in client_list:
               json_attr.append({'client_ip' : key})
        else:
            for key in client_list:
               json_attr.append({'client_start_ip' : key[0], 'client_end_ip' : key[1]})
 
        params = {"is_enable": is_enable,
                  "is_range": is_range,
                  "attr": json_attr }

        return self._transmit("enable_disable_client", params)
```

**Comment by vineetbvp** [comment]
> Hi @vineetbvp
> Almost there,a few minor comments
> 1.
> The following lines (with the same comments) repeat twice in the code, please consolidate it to one function in the `CClientPool` object
> 
> ```
>         /*
>           1. Associate this pool with client object. Store in m_ref_pool_ptr
>           2. Create a DLL node , store this node in m_active_c_node list and then put into active client list of the pool
>           3. Mark it active so that traffic can flow
>         */
>         m_ip_info[i]->add_ref_pool_ptr(this);
>         ActiveClientListNode *cn = m_ip_info[i]->add_client_list_node(m_ip_info[i]);
>         set_client_active(m_ip_info[i], cn, true);
> ```
> 
> or it is better to consolidate `CClientPool::allocate_simple_clients` and `CClientPool::allocate_configured_clients` functions to one (as there is a duplication, including your function)
> 
> 
> `TrexRpcCmdEnableDisableClient::_run(const Json::Value &params, Json::Value &result) {`
> 
> In case of range, you are building a vector and send it to all cores, this make sense in case of a random list, but in case of range just send the range
> 
> ```
>         for (uint32_t client_ip = client_start_ip; client_ip <= client_end_ip; client_ip++)
>             msg_data.push_back(client_ip);
> ```
> 
> 
> TrexRpcCmdGetClientsInfo::_run(const Json::Value &params, Json::Value &result) {
> 
> ```
>         for (uint32_t client_ip = client_start_ip; client_ip <= client_end_ip; client_ip++){
>             for (int thread_id = 0; thread_id < cpu_util_full.size(); thread_id++) {
> 
>                 CTupleGeneratorSmart* ctg = astf_db->get_smart_gen(thread_id);
>                 CFlowGenListPerThread *m_thread_ptr = ctg->get_client_flow_gen_list();
>             
>                 CIpInfoBase *ip_info = m_thread_ptr->client_lookup(client_ip);  <<<<<<<<<<<<<<<< you can't do this!!!
>                 res[to_string(client_ip)] = client_data_to_json(ip_info);
> 
>                 if (ip_info) /* Found no need to look in other thread */
>                    break;
>             } 
>         }
> ```
> 
> You can't manipulate and call function of each core object. It can be accessed only by the DP core else there would be a race. better to send a DP message to each core and wait for a response and merge all the responses.
> 
>     1. better to have a version of the API and a better doc
> 
> 
> enable_clients(self, client_list, is_enable):
> enable_clients(self, client_start, client_end,is_enable):
> 
> ```
>     # execute 'method' for Making  a client active/inactive
>     def enable_disable_client(self, client_list, is_enable, is_range):
>         ''' 
>         API to toggle state of client
>         Input: List of client or list of client range and Action : state flag
>         '''
> 
>         json_attr = []
>         if is_range is False:
>             for key in client_list:
>                json_attr.append({'client_ip' : key})
>         else:
>             for key in client_list:
>                json_attr.append({'client_start_ip' : key[0], 'client_end_ip' : key[1]})
>  
>         params = {"is_enable": is_enable,
>                   "is_range": is_range,
>                   "attr": json_attr }
> 
>         return self._transmit("enable_disable_client", params)
> ```

Fixed Comments 1 ,2 and 4 and pushed changes.
Working on comment 3.

**Comment by vineetbvp** [comment]
Comment 3 addressed in new commit: Get clients information using making calls from CP to DP

**Comment by hhaim** [comment]
@vineetbvp looks good. 
for 4, I would change the API name instead  
```enable_disable_client_v1(self, client_list, is_enable):```
```enable_disable_client_v2(self, client_start, client_end, is_enable):```

call it 

```set_client_enable(self, client_list, is_enable):```
```set_client_enable_range(self, client_start, client_end, is_enable):```

The same for "get_info_v2"

recheck

**Comment by hhaim** [comment]
@vineetbvp I will trigger the regression on this branch

**Comment by hhaim** [comment]
@vineetbvp it is the process to be committed, don't add more commits to this branch. 
I would add documentation 
* How to use from Console
* Limitation (number of ports)

**Comment by hhaim** [comment]
@vineetbvp it was rebased, please commit the new stuf into a new branch

**Pull request closed without merging**
