### PR TITLE
Update trex_faq.asciidoc

### PR DESCRIPTION
**Pull request by digger-yu**
Fixed a digital error in the document ,Modify 2038 to 2048

### CODE REVIEW

**Comment by bdollma** [comment]
@digger-yu I said only the last line, not two lines. The 8000 was ok.

**Comment by digger-yu** [comment]
thanks , After being reminded, the wrong place has been corrected

**Comment by hhaim** [comment]
@digger-yu could you create one PR for all the issue you found?

**Comment by digger-yu** [comment]
@hhaim Sure, I'll turn this off first

**Pull request closed without merging**
