### PR TITLE
add --new-memory option to build with new DPDK memory subsystem.

### PR DESCRIPTION
**Pull request by jsmoon**
Hi, this PR is an implementation of issue #480.

I added generated dpdk_config.h to override RTE_EAL_NUMA_AWARE_HUGEPAGES configuration in rte_config.h dynamically.
```
cd linux_dpdk/
./b configure --new-memory
./b build
```
@hhaim what do you think about this change?

### CODE REVIEW

**Comment by hhaim** [comment]
@jsmoon looks good

**Comment by jsmoon** [comment]
@hhaim, should I do something more for this PR?

**Comment by hhaim** [comment]
@egwakim it looks good. I just on PTO this week due to holiday in israel

**Comment by hhaim** [comment]
rebased

**Comment by LucLemieuxNovi** [comment]
How would i use this, i am trying to get TRex 4 ports running but wathever hugepages config i put it says not enough... How much is required for 4 ports TRex? 
If I try with this new-memory trigger could it help? I'm running on a 24 core 64Gb ram with 4 x 100Gb interfaces E810 ICE drivers.

Works with 2 interfaces no problems.

Thank you!

**Pull request closed without merging**
