### PR TITLE
Fix #808 Invalid config register when updating router image

### LINKED ISSUE #808: invalid config register when updating router image
https://github.com/cisco-system-traffic-generator/trex-core/blob/400f03c86c844a0096dff3f6b13e58a808aaefff/scripts/automation/regression/CPlatform.py#L1015

`0x2021` is an invalid value for config register, it should probably be `0x2102`

https://www.cisco.com/c/en/us/support/docs/routers/10000-series-routers/50421-config-register-use.html

### PR DESCRIPTION
**Pull request by jabir366**
0x2021 was an invalid value for config register. change it to 0x2102

Signed-off-by: Jabir Ali V <jabir366@gmail.com>

### CODE REVIEW

**Comment by bdollma** [comment]
There seems to be a problem with our Jenkins.

**Comment by bdollma** [comment]
recheck

**Comment by jabir366** [comment]
> recheck

What am I supposed to do for initiating the build again?

**Comment by bdollma** [comment]
Nothing, the recheck comment initiated the build again and it passed. Thanks for contributing.

**Comment by hhaim** [comment]
rebased

**Pull request closed without merging**
