### PR TITLE
remove STL profile delayed start possibility

### PR DESCRIPTION
**Pull request by jsmoon**
Hi, this PR is an implementation for #569.
I tried to keep backward compatibility.

@hhaim please check my changes and give your feedback.

### CODE REVIEW

**Comment by hhaim** [comment]
rebased. 
Don't you want the same in ASTF?

**Comment by jsmoon** [comment]
@hhaim No same issue in ASTF.

**Comment by hhaim** [comment]
@jsmoon I've found an issue on slow setup
```
        if (!start_at_ts) {
            start_at_ts = cur_time + schd_offset;
        }
```

This code change the timing in case of single profile with start of two ports (on the same core).
The second time the start_ts is not current time it is current +schd_offset. 
I don't think that start_at_ts is useful and not sure why you override it.
removing this code fix the issue on those setups

**Comment by jsmoon** [comment]
@hhaim since `add_stream` refers the `start_at_ts` like as following.
```
    if ( likely(start_at_ts) ) {
        node->m_time = start_at_ts + stream->get_start_delay_sec();
    } else {
        node->m_time = m_core->m_cur_time_sec + stream->get_start_delay_sec();
    }
```
I don't think it breaks the backward compatibility.
As far as I understood, `start_at_ts` came from the user's request.
So, I thought I can use it when the user does not specify it.

**Comment by hhaim** [comment]
You are right in case ```m_state != TrexStatelessDpCore::STATE_TRANSMITTING```
The issue is in case ```m_state == TrexStatelessDpCore::STATE_TRANSMITTING`` which happen on the second profile on the same core (port 1 start after port 0 start), there is no need to have multi-profile to get to this issue. 

look into this example the duration of the test is 0.1 sec which make the test fail 
```
transmit | cur_time | offset | node-time 
=================================
  false  |   7      |  0.2   |  7+0.2
  true   |   8      |  0.2   |  8 (your code it is 8+0.2) 
```
In the second line the node-time would be 7 and with your code it would be cur_time + offset 

In the old code, we have updated the cur_time with now() and this is not the case anymore.

**Comment by jsmoon** [comment]
@hhaim I missed the case.
I think the following code change would remove this issue.
```
--- a/src/stx/stl/trex_stl_dp_core.cpp
+++ b/src/stx/stl/trex_stl_dp_core.cpp
@@ -1490,7 +1490,7 @@ TrexStatelessDpCore::start_traffic(TrexStreamsCompiledObj *obj,
         double cur_time = m_core->m_cur_time_sec;
         if (m_state != TrexStatelessDpCore::STATE_TRANSMITTING) {
             cur_time = now_sec();
-            m_core->m_cur_time_sec = cur_time + schd_offset;
+            m_core->m_cur_time_sec = cur_time;
         }
         if (!start_at_ts) {
             start_at_ts = cur_time + schd_offset;
@@ -1530,6 +1530,9 @@ TrexStatelessDpCore::start_traffic(TrexStreamsCompiledObj *obj,
 
 
     if ( duration > 0.0 ){
+        if (start_at_ts > m_core->m_cur_time_sec) {
+            duration += (start_at_ts - m_core->m_cur_time_sec);
+        }
         add_port_duration( duration ,obj->get_port_id(), profile_id, event_id );
     }
 
```
Since `add_port_duration` refers to `m_core->m_cur_time_sec` internally, the adjustment based on node-time(start_at_ts) is needed to keep the exact duration.

**Comment by jsmoon** [comment]
@hhaim I'm sorry for your inconvenience.
I know you already solved this issue.
Since you removed setting `start_at_ts`, I think you need to revert `likely(start_at_ts)` to `unlikely(start_at_ts)` also.

Anyway, what do you think about the change cf31f92?

**Pull request closed without merging**
