### PR TITLE
memif: enable loopback

### PR DESCRIPTION
**Pull request by juliusmilan**
Signed-off-by: Július Milan <julius.milan@pantheon.tech>

### CODE REVIEW

**Comment by juliusmilan** [comment]
I discovered another minor problem with memif PMD, the memif socket must be removed every time before running trex as:
sudo rm /run/memif.sock

**Comment by juliusmilan** [comment]
Please don't merge this, it's just for testing purposes, I submitted the same patch to DPDK but it has some problem and was returned yet. I will send you better fix soon.

**Comment by hhaim** [comment]
@juliusmilan thanks for the effort. I this this memif loopback option would be very good for demos

**Comment by juliusmilan** [comment]
Hi Hanoch, just quick update, I sent next patches to DPDK, waiting for their response, will let you know.

**Pull request closed without merging**
