### PR TITLE
Added measured traffic duration per ASTF profile

### PR DESCRIPTION
**Pull request by jsmoon**
Hi, I prepared this PR for issue #464.

@hhaim, please check my changes and give your feedback.

### CODE REVIEW

**Comment by hhaim** [comment]
@jsmoon looks good. DMZ setup does not work for some reason

**Comment by jsmoon** [comment]
@hhaim I missed the update of m_base_time for TCP l7_map case. I added it just before.

**Comment by ybrustin** [comment]
recheck

**Comment by ybrustin** [comment]
recheck

**Comment by ybrustin** [comment]
recheck

**Comment by ybrustin** [comment]
Sorry for the noise of false reports, there was a problem in DMZ setup.
Now seems fixed.
Latest failure is about performance, @hhaim, please review.

**Comment by hhaim** [comment]
rebased

**Pull request closed without merging**
