### PR TITLE
ASTFProgram can send by size and fill.

### PR DESCRIPTION
**Pull request by jsmoon**
Hi @hhaim, This PR is an implementation of suggested issue #401.

```
prog.send(buf, size=1000, fill='*')
```

Please check my changes and give your opinion.

### CODE REVIEW

**Comment by egwakim** [comment]
Hi @hhaim ,
Can you review this code?
It's suggested feature in https://github.com/cisco-system-traffic-generator/trex-core/issues/401

Best Regards
Gwangmoon

**Comment by jsmoon** [comment]
@hhaim I'd like to know when you can review this PR.

**Comment by hhaim** [comment]
@jsmoon I'm adjusting to the quarantine due to Coronavirus. Sorry for the delay.  
Hope to get to it

**Comment by hhaim** [comment]
@jsmoon nice work. Could reduce the json size. 
rebased.

**Pull request closed without merging**
