### PR TITLE
get TCP flow information per profile

### PR DESCRIPTION
**Pull request by jsmoon**
Hi, this is the change for my suggestion in #834.

The user can get the information about a TCP flow per given tg_id.
It includes almost all the FreeBSD `struct tcp_info` information.

@hhaim please review my change and give your feedback.

### CODE REVIEW

**Comment by hhaim** [comment]
@jsmoon, I expect a message from ```TrexRpcCmdAstfGetFlowInfo``` CP->DP to collect the the flow info (as json). the flow could be closed by the time the CP is reading the data.

**Comment by jsmoon** [comment]
@hhaim, I missed that point. I think I can add a sanity check if the flow is closed during the JSON dump.
When it is closed, the JSON dump will be discarded because it could be garbage. I'll update it tomorrow.

**Comment by hhaim** [comment]
@jsmoon it is not advised to do this. Better to add CP->DP message as the flow memory is not protected with memory barrier, so you could have a race of free and read by CP

**Comment by jsmoon** [comment]
@hhaim if I understand correctly, you are concerned CP might access the freed memory and cause a segmentation fault.
But I'd like to avoid the CP<->DP messages for this feature due to the DP performance impact.
So I think I can get the information fast enough to avoid the situation before the flow is closed.
Currently, while the flow is closing, DP clears the flow pointer and calls Delete(), and then deletes the flow.
If I copy the flow memory before the JSON dump, I guess that the memory access can be finished before the flow is deleted.

If you think this way still does not guarantee safer access, I can consider adding a memory barrier in CTcpFlow.

What do you think about this?

**Comment by hhaim** [comment]
@jsmoon 

> avoid the CP<->DP messages for this feature due to the DP performance impact.

I don't see why there would be a DP performance issue? dumping the flow  stats in DP context **only** when RPC is called (rare not every packet) should not have any performance effect. 

When CP reads share information from DP, usually this is a memory that was allocated once and there is a **no** need for memory barrier (e.g. counters)

**Comment by jsmoon** [comment]
@hhaim I mentioned the "DP performance impact" as the DP core interference by CP<->DP message handling. Please ignore the "performance" wording.
And I think I misused the term "memory barrier". I meant it to the protection mechanism preventing freed memory access.

Frankly speaking, I followed the "get_tg_id_stats" implementation. It gathers the statistics counters from DP memory directly in the CP core. I thought that this way minimizes the DP core interference. So I thought that solving the issue of illegal memory access was the key.
What is the difference between "get_tg_id_stats" and "get_flow_info" from your point of view?

**Comment by hhaim** [comment]
@jsmoon the memory for tpgids (```get_tg_id_stats``` ) is allocated once per profile and there is a memory barrier (state-machine) when the profile is removed. If you remember there were a number of issues with illegal memory access into the counters memory. When you share data betwean two cores it is dangerous and there should be a good reason for it. 

In case of flow, you don't want to create a new protection mechanism (e.g. State-machine) for each new flow creation --> this will have a performance issue. 
The simplest way is to have CP->DP messaging as this is not a hot spot.

**Comment by jsmoon** [comment]
@hhaim there is no issue when CP gets the flow pointer in the profile.
The only problem is the possibility that DP can free the flow memory while CP is reading it, as you mentioned at first.
I agree that CP<->DP message is the simplest way.
But, in my opinion, if we can handle the shared data carefully and definitely, it will be worth trying it.
If I could solve the issue with shared data without performance issues, could I try it anyway?

**Comment by jsmoon** [comment]
@hhaim, when I revisited your suggestion, CP->DP message, I realized that there is no simple way to get the response.
AFAIK, in ASTF, all the CP->DP messages do not wait for responses.
CP master thread collects the reply messages asynchronous way and reports it through async_port.
It is rather complex to me.
I think the CP->DP message is not appropriate for the RPC request which requires JSON results in the response message.

**Comment by jsmoon** [comment]
@hhaim, I updated my change to protect against illegal memory access using spinlock.
Do you still want me to add the CP->DP message?
Then, could you give me any ideas on how the client receives the result of "get_flow_info"?

**Comment by hhaim** [comment]
Your code does not solve the problem and could create a crash see snipets,  and I don't want maintainer to keep thinking about this corner case. 
The current concept is simple: flows are created, free and accessed **only by DP** this has the advantage that you don't have false sharing on flows memory and can't have access to a flow that have been freed. 
Let's keep this concept and don't add corner case because we have a minor feature to read only flow statistic. 
the flow-stats should  be sent async to CP and CP can handle it


**The issue**:
 
```TrexRpcCmdAstfGetFlowInfo

  ->DumpTGFlows()
     ->dump_tg_flows()
       for (int i = 0; i < m_profile_ctx.size(); i++) {
	   pctx->get_tcp_info(tcp_info, tg_id); <<
       }

	
	CP->(time 0)
================

        if (flow && !flow->is_can_close()) { <<<(1) this is done without protection
		
			
	
            /* flow memory should be protected from DP free during CP access */
            CSpinLock slock(&m_tcpstat.m_tg_locks[flow->m_tg_id]);
            tcp_info.update_info(flow);


	from DP->(time 1)
================
(2) call free_flow() and finish this function (lock/unlock) the pointer in the vector is null 

HOT_FUNC void CFlowTable::free_flow(CFlowBase * flow){
    assert(flow);
    CPerProfileCtx* pctx = flow->m_pctx;
    flow->m_pctx->m_flow_cnt--;
    flow->m_pctx->on_flow_close();

    if ( flow->is_udp() ){
        CUdpFlow * udp_flow=(CUdpFlow *)flow;
        udp_flow->Delete();
        delete udp_flow;
    }else{
        CTcpFlow * tcp_flow=(CTcpFlow *)flow;
        tcp_flow->m_pctx->clear_flow_info(tcp_flow);
        tcp_flow->Delete();
        delete tcp_flow;  <<<<<<<<<<<<< this is called (lock unlock was already done)
    }



	CP->(time 2)
================
        CTcpFlow* flow = m_tcpstat.m_tg_flows[tg_id];  << this flow is not valid anymore, was removed and freed!!!!


                 if (flow && !flow->is_can_close()) { 
			
	
            CSpinLock slock(&m_tcpstat.m_tg_locks[flow->m_tg_id]);   <<<3 lock pass and flow was freed already 
            tcp_info.update_info(flow);  << update crash the flow is already freed 

```

**Comment by jsmoon** [comment]
@hhaim thank you for your quick review. I updated my change.

> Let's keep this concept and don't add corner case because we have a minor feature to read only flow statistic.
the flow-stats should be sent async to CP and CP can handle it

Although CP can handle it, the client doesn't wait for it under the current mechanism.
In my experience, the DP->CP async message handling was quite complex.

**Comment by hhaim** [comment]
@jsmoon it should be simple in this counters case. 
```CP->DP``` ask to send all the counters vector 
```DP->CP``` (each DP sends the vector ) async
CP < add the counters to a vector and turn **bit** for each core
once all the cores bitmask is on, you can read the vector of counters (and convert them to json)

**Comment by jsmoon** [comment]
@hhaim I know the mechanism, but mainly I want to know the client get the data.
As far as I know, there is no way currently.
I don't want to get the data asynchronousely. It forces the client's additional handling. I don't want it.

**Comment by hhaim** [comment]
@jsmoon the client should have the **same** blocking API (```get_tcp_flow_counters()```)
inside this client API you should have two RPC API to the server 

``` rpc_start_counter_reading()
    while True:
      if rpc_pool_counter_reading() == finish: (this API pool the core bitmask once they all up, read the data)
          break;
```
     
as the CP can't wait infinitely. 

You can simplify this by having one API and  let the CP to wait for a short time for all the results (in most cases it will work), but in rare cases return EAGAIN so the client should return the call

**Comment by egwakim** [comment]
Hi all,
I see that there are different opinion about method to refer data between CP and DP.
"Messaging vs Direct access"

According to the @h's opinion
1) Messaging can solve illegal access issue in smooth way
According to @jsmoon 's opinion
It's heavier than direct access and it requires quite big change because it's differ from current way of accessing TCP statitics, we need to invent new way of accessing DP.

According to @hhaim 's opinion
It's light and simple enough to change

2) Direct access would requires some locking to prevent illegal access
According to @jsmoon 's opinion,
It's simple, lighter and align with current way of accessing TCP statistics

There is different opinion for the amount of required changes and weight in messaging method.
There will be no issue if we have simple and light solution for it.

Hi @hhaim 
Would it possible to suggest more detailed way of messaging method(Light and simple)?
Maybe code level suggestion would be very welcome.

**Comment by egwakim** [comment]
Hi @hhaim 
How about your opinion?
Do you have detailed insight about it?

**Comment by hhaim** [comment]
@egwakim the solution suggested by @jsmoon  ( spinlock) does not solve the problem and can **crash** the server. 

>> @hhaim this is the new way which is different to the current mechanism. Do you really want me to add this way for this feature?
Since the client has timeout for the response waiting, I should stop waiting for the DP response before timeout. Rarely the response can be mixed to the next request. And I should add the response to the DP idle state.
To my thought, it's not simple as you said. Your suggestion requires more considerations due to communication timing issue.
If I must do it this time as you suggested, I cannot help asking this question. Do you have plan to.improve all the statistics implementation to the right way also? To me, DP profile statistics has no different if I dedicated the selected flow memory to the profile by separated memory manager or locking.
If you have plan to do it. I agree that the new mechanism is worth doing it.

@jsmoon to answer your questions, My suggestion is the standard way to solve the problem. Dynamic counters  already use this type of solution. 

One more suggestion, I think that you can use the dynamic counter mechanism (that GTPU uses) could you have a look into this (add/remove set of counters in DP with names that map to tpgid) 

sharing flow memory betwean CP-DP is **not** an option

**Comment by jsmoon** [comment]
@hhaim according to your suggestion, I think I can implement based on the following diagram.
image

**Comment by jsmoon** [comment]
@hhaim,
> @jsmoon to answer your questions, My suggestion is the standard way to solve the problem. Dynamic counters already use this type of solution.
> 
> One more suggestion, I think that you can use the dynamic counter mechanism (that GTPU uses) could you have a look into this (add/remove set of counters in DP with names that map to tpgid)

This PR is not implemented to provide the **counters**. It is to provide the **TCP status** including TCP state at a certain time.
I think you are still seeing this feature as **statistics**.
I thought you agreed that the statistics feature is another story in your comment, "understood" [https://github.com/cisco-system-traffic-generator/trex-core/issues/834#issuecomment-1108276284] for my comment [https://github.com/cisco-system-traffic-generator/trex-core/issues/834#issuecomment-1099879711].
So, this PR is implemented based on thoughts of TCP flow inspection by the user.

If you want to get your statistics feature, please comment that on the original thread #834 and reject this PR, or suggest it in another new thread.
For the statistics feature implementation, I'll check your suggestion later.

> sharing flow memory betwean CP-DP is not an option

sharing flow memory between CP-DP should not be allowed, but sharing profile memory has no problem.
@hhaim, can I think of your answer like this? please confirm sharing profile memory.

> the solution suggested by @jsmoon ( spinlock) does not solve the problem and can crash the server.

My last commit is using mutex lock and I think I removed the crash possibility that you pointed out. I missed the other threads are running in the CP core at that time.
What makes you think that it still causes a crash?

**Comment by hhaim** [comment]
@egwakim I understand your need (status per flow), I am not talking about my aggregated statistics ( e.g. all  flows latency syn-syn/ack). 

>> If you want to get your statistics feature, please comment that on the original thread https://github.com/cisco-system-traffic-generator/trex-core/issues/834 and reject this PR, or suggest it in another new thread.
For the statistics feature implementation, I'll check your suggestion later.

[hh] no, I'm not talking about this


What I've suggested is to use the dynamic-counters infra for the flow-tpgid-status (the **meaning** of the counter would be status). 
This is one option.  Another option is to implement async messaging to get the same API as you have today (from python point of view)


>> My last commit is using mutex lock and I think I removed the crash possibility that you pointed out. I missed the other threads are running in the CP core at that time.
What makes you think that it still causes a crash?

Read the example I gave, there would be a crash with suggested code and even if you fix this, I don't think it wise to use spinlock only for this feature, as this is a dangerous path and contradict the basic way trex works today (almost no sharing of information, only global counters are shared, dynamic **flow** **context** is a different story)

**Comment by jsmoon** [comment]
@hhaim 

> What I've suggested is to use the dynamic-counters infra for the flow-tpgid-status (the meaning of the counter would be status).
This is one option.

Frankly speaking, I don't know about the dynamic-counters infra what you said already used for GTPU counters.
Could you elaborate on how the dynamic-counters infra can cover the `struct tcp_info`?

> Another option is to implement async messaging to get the same API as you have today (from python point of view)

Does this mean that **you can agree with my latest suggestion** depicted in the https://github.com/cisco-system-traffic-generator/trex-core/pull/841#issuecomment-1115856129 diagram?

> Read the example I gave, there would be a crash with suggested code

I think I've fixed it already as I have mentioned at https://github.com/cisco-system-traffic-generator/trex-core/pull/841#issuecomment-1111891153. With this change, the flow pointer in get_tcp_info() will be null during the lock is acquired after clear_flow() has been done. Please check [5b38c87](https://github.com/cisco-system-traffic-generator/trex-core/commit/5b38c876069ad1ea4b7ad46e21365fe2b47ade37).

> and even if you fix this, I don't think it wise to use spinlock only for this feature, as this is a dangerous path 

What do you see as the dangerous path? spinlock usage? sharing dynamic flow memory?

> and contradict the basic way trex works today (almost no sharing of information, only global counters are shared, dynamic flow context is a different story)

As far as I know, DP profile statistics counters are not global counters. But they are shared between CP and DP. So, I can hardly agree with you on this point of view.

I don't think my change is the right way, but I don't think it is the wrong way. I think it is a possible way can be considered. If I understand correctly, your concern is not on the memory sharing itself, but you are concerned about the sharing of the dynamic memory. right?

Finally, I've proposed a new way to change as you suggested I think. Please confirm if you agree with that or not.

**Comment by jsmoon** [comment]
@hhaim I looked into the dynamic counter shortly. I found the following code added a few months ago.
```
1095     uint8_t dp_core_count = astf->get_dp_core_count();
1096     DpsDynSts dp_sts;
1097     for (uint8_t core_id = 0; core_id < dp_core_count; core_id++) {
1098         static MsgReply<dp_sts_t> reply;
1099         reply.reset();
1100         TrexCpToDpMsgBase *msg = new TrexAstfDpInitTunnelHandler(activate, tunnel_type, loopback, reply);
1101         astf->send_msg_to_dp(core_id, msg);
1102         dp_sts.add_dp_dyn_sts(reply.wait_for_reply());
1103     }
```
The MsgReply<T> had been used for the request and reply with RX core. Your intention was to use this way for this feature?
I have thought that it is not designed to communicate with DP cores, so I gave up to use it this way.
If you don't mind this way, I'll change this PR with this right away.

**Comment by hhaim** [comment]
@jsmoon, good point, actually I was wrong with this example, the example of ```dynamic_counters``` is not the right example. In this case we assume there is **no traffic** and no profiles so we can **wait** for messages response (no profile at all). We started by having async activation but we simplify it as there was no request for multiple profile for GTPU (we will need to fix this in the future, make the activation async if requested) 

see this:
```
    TrexAstf *astf = get_astf_object();
    bool is_idle = (astf->get_state() == AstfProfileState::STATE_IDLE) ? true : false;

    if (!is_idle) {
        generate_execute_err(result, "The server state should be IDLE");
    }

```

in **your** case you can't asume it.

The right example (that actually similar to your need) is this:

```
TREX_RPC_CMD(TrexRpcCmdGetClientsInfoStart, "get_clients_info_start");
TREX_RPC_CMD(TrexRpcCmdGetClientsInfoPull, "get_clients_info_pull");

```

(ClientsInfoStart) ask the data (async)
ClientsInfoPull waits for it. 

BTW, before this implementation, there was similar implementation to what you did

in ASTF we can't wait for message reply if there is traffic or if we load a profile. 
```reply.wait_for_reply()```

let me know if you want me to investigate your old fixed code (with spinlock) or better change the code to make the response in async way (like client status)

**Comment by jsmoon** [comment]
@hhaim, according to your last comment, I think https://github.com/cisco-system-traffic-generator/trex-core/pull/841#issuecomment-1115856129 is better. I'll prepare for it.

**Comment by hhaim** [comment]
@jsmoon looks good!


Minor comments:
1. because the DP->CP is async, you should handle the case that there is no profile (it was removed) 
with the current code has an unhandled exception, better to just drop the message 

```
void TrexAstf::add_flows_info(profile_id_t dp_profile_id, Json::Value& flows) {
    get_profile(get_profile_id(dp_profile_id))->add_flow_info(flows);
}
```

2. There is no need to add another node to the low level scheduler only for this feature. Just use timer object that work on top of it, 

```
        dump_node->m_type = CGenNode::TCP_FLOW_DUMP;
```

See example how to use the timer_wheel in DP 


```
CAstfFifRampup::CAstfFifRampup(CPerProfileCtx * pctx,
                   uint16_t           rampup_sec,
                   double             cps){
        /* total ticks */
        m_pctx = pctx;
        m_ctx = pctx->m_ctx;
        m_ticks = (uint32_t)rampup_sec*1000/TICK_MSEC;
        m_rampup_sec =rampup_sec;
        assert(m_ticks>1);
        m_cur_tick = 1;
        m_cps = cps;
        m_tmr = new CAstfTimerFunctorObj();
        assert(m_tmr);
        m_tmr->m_cb = std::bind(&CAstfFifRampup::on_timer_update,this,m_tmr);
        on_timer_update(m_tmr);
}

```

**Comment by hhaim** [comment]
rebased

**Pull request closed without merging**
