### PR TITLE
Fix dummy rx function used when AVX512F CPU feature available.

### PR DESCRIPTION
**Pull request by jsmoon**
This change will solve the ARP issue in #148.

### CODE REVIEW

**Comment by hhaim** [comment]
rebased

**Comment by hhaim** [comment]
The performance was reduced by 20% in STL mode. I've change the CL a bit to fix this

**Comment by hhaim** [comment]
Could you test the latest code. I've change the code to fix a regression performance issue

**Comment by jsmoon** [comment]
I've tested with latest code. ARP issue was gone and regarding performance
issue was not shown.
Actually I didn't met the performance issue you mentioned.
So, I cannot understand why your code can fix the performance issue.
Could you explain the performance issue in detail?

**Comment by hhaim** [comment]
We have 24/7 regressions setup. the X710 setup with 16 ports shows 30% degradation in STL tests (in the ELK database).  I don't understand why it happen but changing the code as I did fix the issue.

**Pull request closed without merging**
