### PR TITLE
From STL_Profile_Regression_Test_Refinement for travis regressiont test 

### PR DESCRIPTION
**Pull request by elados93**
This is a follow up from: [pr 262](https://github.com/cisco-system-traffic-generator/trex-core/pull/262)

### CODE REVIEW

**Comment by hhaim** [comment]
trex-08 does not work (XL710) while trex-09 (X710) works.
it might be related to the fact that trex-08 is connected like this

0->3
1->2
2->1
3->0

Instead of (trex-09)

0->1
1->0
2->3
2->2

This has more race conditions than the normal when one core handles both 0,1 2,3

**Comment by hhaim** [comment]
the other type of error 
```~1000000pps, got: 785791.6``` 
Could be fixed by adding a specific test tunable per setup 

see example here 

you should add an object to this file 
https://github.com/cisco-system-traffic-generator/trex-core/blob/master/scripts/automation/regression/setups/trex08/benchmark.yaml#L234

and use it in the test like this 

it  take the per test tunable from the benchmark.yaml 

```
        dp_cores     = self.stl_trex.system_info.get('dp_core_count', 0)
```

**Comment by JunsubHan4rmEricsson** [comment]
I think the problem was due to such high PPS for 100 profiles. 
I've decreased the PPS for test cases, 
**1) test_pause_resume_update_dynamic_profile
2) test_pause_resume_update_streams**

**Comment by JunsubHan4rmEricsson** [comment]
> the other type of error
> `~1000000pps, got: 785791.6`
> Could be fixed by adding a specific test tunable per setup
> 
> see example here
> 
> you should add an object to this file
> https://github.com/cisco-system-traffic-generator/trex-core/blob/master/scripts/automation/regression/setups/trex08/benchmark.yaml#L234
> 
> and use it in the test like this
> 
> it take the per test tunable from the benchmark.yaml
> 
> ```
>         dp_cores     = self.stl_trex.system_info.get('dp_core_count', 0)
> ```

I think the problem was due to such high PPS for 100 profiles. 
I've decreased the PPS for test cases, 
**1) test_pause_resume_update_dynamic_profile
2) test_pause_resume_update_streams**

**Comment by JunsubHan4rmEricsson** [comment]
> trex-08 does not work (XL710) while trex-09 (X710) works.
> it might be related to the fact that trex-08 is connected like this
> 
> 0->3
> 1->2
> 2->1
> 3->0
> 
> Instead of (trex-09)
> 
> 0->1
> 1->0
> 2->3
> 2->2
> 
> This has more race conditions than the normal when one core handles both 0,1 2,3

What do you suggest I do for this?
It seems to do with your test setup

**Comment by hhaim** [comment]
> > the other type of error
> > `~1000000pps, got: 785791.6`
> > Could be fixed by adding a specific test tunable per setup
> > see example here
> > you should add an object to this file
> > https://github.com/cisco-system-traffic-generator/trex-core/blob/master/scripts/automation/regression/setups/trex08/benchmark.yaml#L234
> > and use it in the test like this
> > it take the per test tunable from the benchmark.yaml
> > ```
> >         dp_cores     = self.stl_trex.system_info.get('dp_core_count', 0)
> > ```
> 
> I think the problem was due to such high PPS for 100 profiles.
> I've decreased the PPS for test cases,
> **1) test_pause_resume_update_dynamic_profile 2) test_pause_resume_update_streams**

This is not the right way to solve this problem. There are setups that are very slow (10PPS), does it mean that 100mpps setup will test with the same rate? 
Have a look how I suggested to solve this.

**Comment by hhaim** [comment]
> > trex-08 does not work (XL710) while trex-09 (X710) works.
> > it might be related to the fact that trex-08 is connected like this
> > 0->3
> > 1->2
> > 2->1
> > 3->0
> > Instead of (trex-09)
> > 0->1
> > 1->0
> > 2->3
> > 2->2
> > This has more race conditions than the normal when one core handles both 0,1 2,3
> 
> What do you suggest I do for this?
> It seems to do with your test setup

This type of setups are more prone to software race conditions. The best way to solve it is to reconstruct with the same setup in your place and find/solve the rate

**Comment by JunsubHan4rmEricsson** [comment]
> > > the other type of error
> > > `~1000000pps, got: 785791.6`
> > > Could be fixed by adding a specific test tunable per setup
> > > see example here
> > > you should add an object to this file
> > > https://github.com/cisco-system-traffic-generator/trex-core/blob/master/scripts/automation/regression/setups/trex08/benchmark.yaml#L234
> > > and use it in the test like this
> > > it take the per test tunable from the benchmark.yaml
> > > ```
> > >         dp_cores     = self.stl_trex.system_info.get('dp_core_count', 0)
> > > ```
> > 
> > 
> > I think the problem was due to such high PPS for 100 profiles.
> > I've decreased the PPS for test cases,
> > **1) test_pause_resume_update_dynamic_profile 2) test_pause_resume_update_streams**
> 
> This is not the right way to solve this problem. There are setups that are very slow (10PPS), does it mean that 100mpps setup will test with the same rate?
> Have a look how I suggested to solve this.

I understand but the original PPS for the first test was just too high. 
Let's look at **test_pause_resume_update_dynamic_profile** for example (the one with the most errors)
Line 747 and line 752 continue to show errors in this test case. 
expected_pps was 1000,000 and 2,000,000 which is just too high. 

These test cases have been passing under 40G setup.
However, under 10G setup (yours) test case continues to show the shortage of PPS
**AssertionError: expected TX ~1000000pps, got: 785791.6**

That is why me and my team members decided to lower the PPS transferred

**Comment by JunsubHan4rmEricsson** [comment]
> > > trex-08 does not work (XL710) while trex-09 (X710) works.
> > > it might be related to the fact that trex-08 is connected like this
> > > 0->3
> > > 1->2
> > > 2->1
> > > 3->0
> > > Instead of (trex-09)
> > > 0->1
> > > 1->0
> > > 2->3
> > > 2->2
> > > This has more race conditions than the normal when one core handles both 0,1 2,3
> > 
> > 
> > What do you suggest I do for this?
> > It seems to do with your test setup
> 
> This type of setups are more prone to software race conditions. The best way to solve it is to reconstruct with the same setup in your place and find/solve the rate

What do you mean rate?
aren't you talking about the pg_id error?
**trex.common.trex_exceptions.TRexError: Port 0 : *** For payload rules: Can't have two streams with same pg_id, or same stream on more than one port**

**Pull request closed without merging**
