### PR TITLE
enable TSO packet dissection of tools

### PR DESCRIPTION
**Pull request by jsmoon**
Hi, as discussed at #975, I prepared this PR which enables TSO packet dissection of tools.
This change allows Wireshark and tcpdump to show TCP header information in the captured TSO packet.

@hhaim please review my change and give your opinion.

### CODE REVIEW

**Comment by jsmoon** [comment]
@hhaim, already 3 weeks passed. How long should I wait for more to get your comment?

**Comment by hhaim** [comment]
@jsmoon sorry for the delay. Did you test this on a setup that has TSO ( XL710)? the pseudo checksum calculation should be fixed too with the same header. I see fix only in one place instead of two.

**Comment by hhaim** [comment]
@jsmoon looking again into the code, the PR is OK.

**Comment by hhaim** [comment]
rebased

**Pull request closed without merging**
