### PR TITLE
I pv6 nd devel

### PR DESCRIPTION
**Pull request by andreasbourges**
Hi Hanoh & TRex-team,

...finally I think that the IPv6ND service implementation is ready for a merge. I have not squashed my commits into a single one (wasn't sure how to best accomplish this), but as far as I saw, this can now be easily accomplished when you would merge this stuff.

best regards,

Andreas

### CODE REVIEW

**Comment by ybrustin** [comment]
./trex-console --python2
...
trex>plugins load IPv6ND
Loading plugin: IPv6ND                                       [FAILED]
Exception during import of console.plugins.plugin_IPv6ND: No module named ipaddr

:camel: :camel: :camel: :camel: :camel: :camel: :camel: 

./trex-console --python3
...
trex>plugins load IPv6ND
Loading plugin: IPv6ND                                       [FAILED]
Exception during import of console.plugins.plugin_IPv6ND: invalid syntax (plugin_IPv6ND.py, line 84)

**Comment by andreasbourges** [comment]
:( should I fix that in my branch and issue a new pull-request?

Thanks,

Andreas

Yaroslav Brustinov <notifications@github.com> schrieb am 14.01.2018:
>./trex-console --python2
>...
>trex>plugins load IPv6ND
>Loading plugin: IPv6ND                                       [FAILED]
>Exception during import of console.plugins.plugin_IPv6ND: No module
>named ipaddr
>
>:camel: :camel: :camel: :camel: :camel: :camel: :camel: 
>
>./trex-console --python3
>...
>trex>plugins load IPv6ND
>Loading plugin: IPv6ND                                       [FAILED]
>Exception during import of console.plugins.plugin_IPv6ND: invalid
>syntax (plugin_IPv6ND.py, line 84)

-- Diese Nachricht wurde mit K-@ Mail gesendet.

**Comment by ybrustin** [comment]
Hi,

Would be nice.

Thanks,
Yaroslav.

**Comment by andreasbourges** [comment]
HI Yaroslav,

I've pushed the changes to my branch on github. Sorry for the inconvenience :(

regards,

Andreas


On Sonntag, 14. Januar 2018 08:36:30 CET Yaroslav Brustinov wrote:
> Hi,
> 
> Would be nice.
> 
> Thanks,
> Yaroslav.


-- 
I think it's a little fantastic to try to form a picture in people's
minds of the Debian archive administration team huddled over their
terminals, their faces lit only by a CRT with a little root shell
prompt and the command
"/project/org/ftp.debian.org/cabal/s3kr1t/nuke-non-free.pl" all keyed
in and ready to go, their fingers poised over the enter key, a sweat of
lustful anticipated beading on their upper lips."
		-- Branden Robinson in
		   <20031104211846.GK13131@deadbeast.net> discussing
		   his draft Social Contract amendment

**Comment by ybrustin** [comment]
Hi,

Thanks for the fixes.
In case of no response, the output is bad:

**Python3:**

```
trex(service)>plugins IPv6ND resolve -p 0 -s fe80::4560:ff:fe01:0 -d fe80::200:ff:fe01:1 -V -t 1 -R 0

performing ND for 1 addresses.
NA response timeout............: 1s
Neighbor verification timeout..: 0s

ND: TX NS: fe80::4560:ff:fe01:0,a0:36:9f:20:e6:ce -> fe80::200:ff:fe01:1 (retry 0)
ND: timeout for fe80::4560:ff:fe01:0,a0:36:9f:20:e6:ce <-- fe80::200:ff:fe01:1 (retry 0)
trex(service)>plugins IPv6ND status


ND Status
---------

used vlan(s)...................: []
used encapsulation.............: None
number of IPv6 source addresses: 1


    SRC MAC              SRC IPv6                 |       DST IPv6                     DST MAC       STATE        VERIFIED
--------------------------------------------------------------------------------------------------------------------------
non-empty format string passed to object.__format__
```

**Python2:**

```
trex(service)>plugins IPv6ND resolve -p 0 -s fe80::4560:ff:fe01:0 -d fe80::200:ff:fe01:1 -V -t 1 -R 0

performing ND for 1 addresses.
NA response timeout............: 1s
Neighbor verification timeout..: 0s

ND: TX NS: fe80::4560:ff:fe01:0,a0:36:9f:20:e6:ce -> fe80::200:ff:fe01:1 (retry 0)
ND: timeout for fe80::4560:ff:fe01:0,a0:36:9f:20:e6:ce <-- fe80::200:ff:fe01:1 (retry 0)
trex(service)>plugins IPv6ND status


ND Status
---------

used vlan(s)...................: []
used encapsulation.............: None
number of IPv6 source addresses: 1


    SRC MAC              SRC IPv6                 |       DST IPv6                     DST MAC       STATE        VERIFIED
--------------------------------------------------------------------------------------------------------------------------
a0:36:9f:20:e6:ce  fe80::4560:ff:fe01:0           | fe80::200:ff:fe01:1            None              UNREACHABLE      0
()
resolved..: 0
unresolved: 1
verified..: 0
()
```

**Comment by andreasbourges** [comment]
Ok, will have a look at it...

Yaroslav Brustinov <notifications@github.com> schrieb am 14.01.2018:
>Hi,
>
>Thanks for the fixes.
>In case of no response, the output is bad:
>
>**Python3:**
>
>```
>trex(service)>plugins IPv6ND resolve -p 0 -s fe80::4560:ff:fe01:0 -d
>fe80::200:ff:fe01:1 -V -t 1 -R 0
>
>performing ND for 1 addresses.
>NA response timeout............: 1s
>Neighbor verification timeout..: 0s
>
>ND: TX NS: fe80::4560:ff:fe01:0,a0:36:9f:20:e6:ce ->
>fe80::200:ff:fe01:1 (retry 0)
>ND: timeout for fe80::4560:ff:fe01:0,a0:36:9f:20:e6:ce <--
>fe80::200:ff:fe01:1 (retry 0)
>trex(service)>plugins IPv6ND status
>
>
>ND Status
>---------
>
>used vlan(s)...................: []
>used encapsulation.............: None
>number of IPv6 source addresses: 1
>
>
>SRC MAC              SRC IPv6                 |       DST IPv6         
>           DST MAC       STATE        VERIFIED
>--------------------------------------------------------------------------------------------------------------------------
>non-empty format string passed to object.__format__
>```
>
>**Python2:**
>
>```
>trex(service)>plugins IPv6ND resolve -p 0 -s fe80::4560:ff:fe01:0 -d
>fe80::200:ff:fe01:1 -V -t 1 -R 0
>
>performing ND for 1 addresses.
>NA response timeout............: 1s
>Neighbor verification timeout..: 0s
>
>ND: TX NS: fe80::4560:ff:fe01:0,a0:36:9f:20:e6:ce ->
>fe80::200:ff:fe01:1 (retry 0)
>ND: timeout for fe80::4560:ff:fe01:0,a0:36:9f:20:e6:ce <--
>fe80::200:ff:fe01:1 (retry 0)
>trex(service)>plugins IPv6ND status
>
>
>ND Status
>---------
>
>used vlan(s)...................: []
>used encapsulation.............: None
>number of IPv6 source addresses: 1
>
>
>SRC MAC              SRC IPv6                 |       DST IPv6         
>           DST MAC       STATE        VERIFIED
>--------------------------------------------------------------------------------------------------------------------------
>a0:36:9f:20:e6:ce  fe80::4560:ff:fe01:0           | fe80::200:ff:fe01:1
>           None              UNREACHABLE      0
>()
>resolved..: 0
>unresolved: 1
>verified..: 0
>()
>```

-- Diese Nachricht wurde mit K-@ Mail gesendet.

**Comment by andreasbourges** [comment]
Hi Yaroslav,

output fixed...

regards,

Andreas

On Sonntag, 14. Januar 2018 16:00:44 CET Yaroslav Brustinov wrote:
> Hi,
> 
> Thanks for the fixes.
> In case of no response, the output is bad:
> 
> **Python3:**
> 
> ```
> trex(service)>plugins IPv6ND resolve -p 0 -s fe80::4560:ff:fe01:0 -d
> fe80::200:ff:fe01:1 -V -t 1 -R 0
> 
> performing ND for 1 addresses.
> NA response timeout............: 1s
> Neighbor verification timeout..: 0s
> 
> ND: TX NS: fe80::4560:ff:fe01:0,a0:36:9f:20:e6:ce -> fe80::200:ff:fe01:1
> (retry 0) ND: timeout for fe80::4560:ff:fe01:0,a0:36:9f:20:e6:ce <--
> fe80::200:ff:fe01:1 (retry 0) trex(service)>plugins IPv6ND status
> 
> 
> ND Status
> ---------
> 
> used vlan(s)...................: []
> used encapsulation.............: None
> number of IPv6 source addresses: 1
> 
> 
>     SRC MAC              SRC IPv6                 |       DST IPv6          
>           DST MAC       STATE        VERIFIED
> ---------------------------------------------------------------------------
> ----------------------------------------------- non-empty format string
> passed to object.__format__
> ```
> 
> **Python2:**
> 
> ```
> trex(service)>plugins IPv6ND resolve -p 0 -s fe80::4560:ff:fe01:0 -d
> fe80::200:ff:fe01:1 -V -t 1 -R 0
> 
> performing ND for 1 addresses.
> NA response timeout............: 1s
> Neighbor verification timeout..: 0s
> 
> ND: TX NS: fe80::4560:ff:fe01:0,a0:36:9f:20:e6:ce -> fe80::200:ff:fe01:1
> (retry 0) ND: timeout for fe80::4560:ff:fe01:0,a0:36:9f:20:e6:ce <--
> fe80::200:ff:fe01:1 (retry 0) trex(service)>plugins IPv6ND status
> 
> 
> ND Status
> ---------
> 
> used vlan(s)...................: []
> used encapsulation.............: None
> number of IPv6 source addresses: 1
> 
> 
>     SRC MAC              SRC IPv6                 |       DST IPv6          
>           DST MAC       STATE        VERIFIED
> ---------------------------------------------------------------------------
> ----------------------------------------------- a0:36:9f:20:e6:ce 
> fe80::4560:ff:fe01:0           | fe80::200:ff:fe01:1            None       
>       UNREACHABLE      0 ()
> resolved..: 0
> unresolved: 1
> verified..: 0
> ()
> ```


-- 
<wolfgang> the problem with the 'go find a real girl' admonition is
           that so few of them actually have naked transformation
           sequences
<reality> Dude, my girlfriend changes like four times a day

**Comment by ybrustin** [comment]
Thanks, will be rebased into next release.

**Comment by hhaim** [comment]
rebased

**Pull request closed without merging**
