### PR TITLE
ASTF: allow different stat counters on clients

### PR DESCRIPTION
**Pull request by fperrin**
Closes: #307

Signed-off-by: Frédéric Perrin <fred@fperrin.net>

### CODE REVIEW

**Comment by ybrustin** [comment]
We have an error in regression report script.
Please sync with latest master as it should fix the issue.

**Comment by fperrin** [comment]
Hi @ybrustin , since the first job failed with an encoding error, I assumed the problem was my name `Frédéric` containing non-ASCII characters. So I resubmitted with the author name changed to `Frederic`. Well trex-bot is happy now, so I won't change it any further.

**Comment by ybrustin** [comment]
Hi,

Encoding-wise its fine.

Regarding the PR itself:
For someone who has many ports (let's say 16) it will mean many RPC requests.

Better to keep it per class, but save the xstat names in dict with key of client_object.ctx.session_id
(Need also to cleanup names upon client disconnect)

Even better, the function get_names can be static and called by client [once] upon connection to return the names.
Afterwards, it will be assigned to all port objects as copy.

**Comment by fperrin** [comment]
If I'm not mistaken get_names is only called from TRexClient._connect(). So the cost of the RPC calls will only be born at the time of connection. Is that too expensive?

I'm not sure you want to index by client ID though. Can you have port 1 on, say, a 10G interface and port 2 on a 25G interface? In that case, we could cache on interface type instead. (Using port_obj.driver? Are all interfaces using a given driver exporting the same set of stats?)

**Comment by hhaim** [comment]
This is the issue, with 32 ports you will run the same RPC 32 times. 
```
   for port in self.ports.values():
            port.xstats.get_names(port)
```

The suggestion  is to read it once for all the ports as it is not supported to have multi type ports in one server.

**Comment by ybrustin** [comment]
> I'm not sure you want to index by client ID though. Can you have port 1 on, say, a 10G interface and port 2 on a 25G interface? In that case, we could cache on interface type instead. (Using port_obj.driver? Are all interfaces using a given driver exporting the same set of stats?)

Per TRex server instance [i.e. per current connection] all names are the same for all ports.

**Comment by fperrin** [comment]
Changed so that the names are fetched once and then copied to all ports accessed by the TRex client.

Second push: python3 dict.values() is not a list.

**Comment by ybrustin** [comment]
Rebased to master with small refactor

**Comment by fperrin** [comment]
Thanks @ybrustin

**Pull request closed without merging**
