### PR TITLE
ASTF dynamic profile is available in CP side

### PR DESCRIPTION
**Pull request by yonghwan007**
The summary of dynamic multiple profile in CP side.

1. Support multiple profiles in CP side
2. Support statisctics for each profile
3. Added new RPC command 'get_total_counter_values' for statistics summary of all profiles
4. Added new event through asynchronous port.
 - EVENT_ASTF_PROFILE_STATE_CHG = 60 : event for each profile state change
 - EVENT_ASTF_PROFILE_CLEARED   = 61 : event for each rofile clear(remove database)
5. Added TrexAstfDeleteDB message between CP and DP to remove CAstfDB.

I have done regression test in our environment.

### CODE REVIEW

**Comment by yonghwan007** [comment]
I have finished full regression on my setups, and all tests were passed.

**Comment by hhaim** [comment]
Hi @yonghwan007 the ASTF DP from @jsmoon has a crash., I'm waiting for a fix . After the fix worth verifying that both patches (CP+DP) does not have this issue.

**Comment by yonghwan007** [comment]
I rebased from master including DP code.
I have done full regression test, and all tests were passed.

**Comment by hhaim** [comment]
Hi @yonghwan007 
please consult with  @jsmoon it seems that reading the counters are not protected as it could be changed by DP. We had a crash in the DP change and the workaround was to create the default context once. 
This workaround won't work for the general case. 
My suggestion for now is to keep only the default profile for now (read only default) and in a diff PR to solve the counters issue 

```
@@ -52,11 +53,11 @@ void CSTTCpPerTGIDPerDir::update_counters(bool is_sum, uint16_t tg_id) {
        uint64_t *base_tcp;
        uint64_t *base_udp;
        if (is_sum) {
            base_tcp = (uint64_t *)&lpctx->get_tcpstat()->m_sts;
            base_udp = (uint64_t *)&lpctx->get_udpstat()->m_sts;
            base_tcp = (uint64_t *)&lpctx->get_tcpstat(m_stt_id)->m_sts;
            base_udp = (uint64_t *)&lpctx->get_udpstat(m_stt_id)->m_sts;

```

**Comment by hhaim** [comment]
BTW regression is OK

**Comment by hhaim** [comment]
```
    void Create(uint32_t stt_id=0, uint16_t num_of_tg_ids=1, bool first_time=true);
```

Understood. The code will work for default profile *but* not for multi-profile. 
Suggest to fix the general case and "remove" case as I proposed in the other thread

**Comment by yonghwan007** [comment]
Okay, I understood.
I am out of office during this week, so I will implement a proper solution for general case on Monday.

**Comment by hhaim** [comment]
rebased.

**Pull request closed without merging**
