### PR TITLE
STF tunneling ip variation (max_ip_tunnels)

### PR DESCRIPTION
**Pull request by jhexan**
I've added a new configuration, max_ip_tunnels, to control the number of unique tunnels by changing the outer IP addresses based on the inner source IP. To calculate the outer IPs I'm using:

tunnel IP = template tunnel IP + (current inner source IP % max_ip_tunnels)

### CODE REVIEW

**Comment by hhaim** [comment]
@jhexan looks good. I see that you are still using the old STF mode. Do you have a plan to move to ASTF?

**Comment by hhaim** [comment]
rebased

**Comment by jhexan** [comment]
We’re using both modes, and still have use cases for STF.

sent from my iphone

**Comment by hhaim** [comment]
So what do you do in case of tunnel and ASTF?

**Comment by jhexan** [comment]
That’s the next thing I’ll be taking a look at :)

**Pull request closed without merging**
