### PR TITLE
Stl dynamic profile

### PR DESCRIPTION
**Pull request by Cyborn-Minjae-Lee**
Hi Cisco team

@Cyborn-Minjae-Lee @egwakim @ejangle @JaeyongYu @jsmoon @JunsubHan4rmEricsson @taewoonyun @yonghwan007 @youngjun1

Let's pull request this code.
It is related to an issue for #181 .
This only for the part of Server side including DP.
Server side was tested with the next Client.
If you want to consider for Client, please refer to https://github.com/bidtt4/trex-core/pull/4/files .
Client, Test and Documents will be pull-requested soon.

Please condsider and feel free to feed back.

BR,
Minjae Lee

### CODE REVIEW

**Comment by hhaim** [comment]
Could this branch work with  older client?
I didn't review it yet, but one question pop up.
I see that the "all-profile" logic (port.*") is in the server -> DP. 
Would the code be simpler if we  moved this complexity to the client (iterate and stop one profile at  a time) I think we need to think about the complexity of the server too.

**Comment by Cyborn-Minjae-Lee** [comment]
Hi Hanoh,

I already had completed the test for backward-compatibility and gtest and regerssion-test.
I think,  the "all-profile *" is needed to improve the performance in a large number of profiles.
How about you?
But, stop method will be updated simply soon.

BR,
Minjae Lee

**Comment by hhaim** [comment]
It does not seem to pass regression

“
Total: 1925, Passed: 773, Error: 204, Failure: 149, Skipped: 799”


Version

**Comment by Cyborn-Minjae-Lee** [comment]
Hi Hanoh,

You might test verious target configurations. 
But, I test only one kind of test target. 
I got same result as before this feature(STL daynamic profile) in my test environment.
   
Could you please let me know critical point or materials to analyze your test results?

BR,
Minjae

**Comment by hhaim** [comment]
All the platforms fails. 
This is from our trex-08 setup (XL710,PF) 
As you can see there is a basic problem. 
"
stateless_tests.stl_client_test.STLClient_Test.test_basic_cont
stateless_tests.stl_client_test.STLClient_Test.test_all_profiles
stateless_tests.stl_client_test.STLClient_Test.test_basic_multi_burst
stateless_tests.stl_client_test.STLClient_Test.test_basic_single_burst
stateless_tests.stl_client_test.STLClient_Test.test_core_pinning
stateless_tests.stl_client_test.STLClient_Test.test_core_pinning_latency
stateless_tests.stl_client_test.STLClient_Test.test_latency_pause_resume
stateless_tests.stl_client_test.STLClient_Test.test_pause_resume_update_streams
stateless_tests.stl_client_test.STLClient_Test.test_pcap_remote
stateless_tests.stl_client_test.STLClient_Test.test_push_pcap
stateless_tests.stl_client_test.STLClient_Test.test_stress_tx
stateless_tests.stl_client_test.STLClient_Test.test_tx_from_rx
stateless_tests.stl_core_id_pinning_test.CoreID_Test.test_core_id_negative
stateless_tests.stl_core_id_pinning_test.CoreID_Test.test_core_id_pinning_several_cores
stateless_tests.stl_core_id_pinning_test.CoreID_Test.test_core_id_pinning_several_streams
stateless_tests.stl_core_id_pinning_test.CoreID_Test.test_core_id_pinning_single
stateless_tests.stl_core_id_pinning_test.CoreID_Test.test_core_id_pinning_single_burst_loop
stateless_tests.stl_examples_test.STLExamples_Test.test_stl_examples
stateless_tests.stl_performance_test.STLPerformance_Test.test_performance_syn_attack_multi_cpus
stateless_tests.stl_performance_test.STLPerformance_Test.test_performance_syn_attack_single_cpu
stateless_tests.stl_performance_test.STLPerformance_Test.test_performance_vm_multi_cpus
stateless_tests.stl_performance_test.STLPerformance_Test.test_performance_vm_multi_cpus_cached
stateless_tests.stl_performance_test.STLPerformance_Test.test_performance_vm_single_cpu
stateless_tests.stl_performance_test.STLPerformance_Test.test_performance_vm_single_cpu_cached
stateless_tests.stl_rx_test.STLRX_Test.test_1_stream_many_iterations
stateless_tests.stl_rx_test.STLRX_Test.test_9k_stream
stateless_tests.stl_rx_test.STLRX_Test.test_fcs_stream
stateless_tests.stl_rx_test.STLRX_Test.test_incremental_latency_streams
stateless_tests.stl_rx_test.STLRX_Test.test_multiple_streams
stateless_tests.stl_rx_test.STLRX_Test.test_multiple_streams_random
stateless_tests.stl_rx_test.STLRX_Test.test_one_stream
stateless_tests.stl_rx_test.STLRX_Test.test_service_mode_flow_stats
stateless_tests.stl_rx_test.STLRX_Test.test_vxlan_fs
stateless_tests.stl_rx_test.STLRX_Test.test_x710_counters_wraparound
stateless_tests.trex_client_pkg_test.CTRexClientPKG_Test.test_client_python2
stateless_tests.trex_client_pkg_test.CTRexClientPKG_Test.test_client_python3
"
I would start with one test something like this

stateless_tests.stl_rx_test.STLRX_Test.test_one_stream

have a look here how to run a regression 
https://github.com/cisco-system-traffic-generator/trex-core/wiki#running-regression

**Comment by Cyborn-Minjae-Lee** [comment]
Hi Hanoh,

 I have double check it. In my test environment, we cannot find any failed case.
Might you test regression with new feature of server only not including Client?  
Please check your configuration.

If you want to be pull-requested seperately the server of CP and DP to solve regression issue, I will.

BR,
Minjae

**Comment by hhaim** [comment]
I’m testing only this PR (without Client code)
Could you create a new PR with Client code so I could re-run it

**Comment by Cyborn-Minjae-Lee** [comment]
I have test only this PR (without Client code) with no problem.
Let's divide code smaller with seperating CP and DP in Server PR to know root cause.
How about your opinion?

BR, Minjae

**Comment by hhaim** [comment]
OK, let me re-check and I will pin point the issue with this branch

**Comment by hhaim** [comment]
I've just sync to latest on this branch 

This is the first test that fails  ```test_basic_multi_burst```

**How to run**

The server like this 

```
./t-rex-64 -i

```

The regression like this 
```
 ./run_regression --stl --no-daemon --skip-clean -t test_basic_multi_burst
 ./run_regression --stl --no-daemon --skip-clean -t test_basic_multi_burst
 ./run_regression --stl --no-daemon --skip-clean -t test_basic_multi_burst
```
The second or last will fail with this error (the first will pass)
```
1) FAIL: test_basic_multi_burst (stateless_tests.stl_client_test.STLClient_Test)

   Traceback (most recent call last):
    stateless_tests/stl_client_test.py line 177 in test_basic_multi_burst
      assert False , '{0}'.format(e)
   AssertionError: port(s) [0, 1]: are active
```


The problem is that the port stuck as active (TRANSMITTING) and the DP does not stop 
```
   port    |         0         |         1         |         2         |         3         |       total       
-----------+-------------------+-------------------+-------------------+-------------------+------------------
owner      |                   |                   |                   |                   |                   
link       |                UP |                UP |                UP |                UP |                   
state      |      TRANSMITTING |      TRANSMITTING |              IDLE |              IDLE |                   
speed      |           10 Gb/s |           10 Gb/s |           10 Gb/s |           10 Gb/s |                   
CPU util.  |              0.0% |              0.0% |              0.0% |              0.0% |                   
--         |                   |                   |                   |                   |                   
Tx bps L2  |             0 bps |             0 bps |             0 bps |             0 bps |             0 bps 
Tx bps L1  |             0 bps |             0 bps |             0 bps |             0 bps |             0 bps 
Tx pps     |             0 pps |             0 pps |             0 pps |             0 pps |             0 pps 
Line Util. |               0 % |               0 % |               0 % |               0 % |                   
---        |                   |                   |                   |                   |                   
Rx bps     |             0 bps |             0 bps |             0 bps |             0 bps |             0 bps 
Rx pps     |             0 pps |             0 pps |             0 pps |             0 pps |             0 pps 
----       |                   |                   |                   |                   |                   
opackets   |              1009 |              1009 |                 9 |                 9 |              2036 
ipackets   |              1012 |              1012 |                12 |                12 |              2048 
obytes     |             83576 |             83576 |               576 |               576 |            168304 
ibytes     |             83768 |             83768 |               768 |               768 |            169072 
tx-pkts    |        1.01 Kpkts |        1.01 Kpkts |            9 pkts |            9 pkts |        2.04 Kpkts 
rx-pkts    |        1.01 Kpkts |        1.01 Kpkts |           12 pkts |           12 pkts |        2.05 Kpkts 
tx-bytes   |          83.58 KB |          83.58 KB |             576 B |             576 B |          168.3 KB 
rx-bytes   |          83.77 KB |          83.77 KB |             768 B |             768 B |         169.07 KB 
-----      |                   |                   |                   |                   |                   
oerrors    |                 0 |                 0 |                 0 |                 0 |                 0 
ierrors    |                 0 |                 0 |                 0 |                 0 |                 0 

status:  -

```

It is consistent 
Please share the results of your test on this branch

**Comment by hhaim** [comment]
It should be easy to debug this issue. It is either DP or CP that stuck in active state. 
the CP should get an event from DP (each thread) and only when all move to IDLE the state of CP change to IDLE

**Comment by hhaim** [comment]
```
class AsyncProfileStopEvent : public TrexDpPortEvent {

protected:
    /**
     * when an async event occurs (all cores have reported in)
     * 
     * @author imarom (29-Feb-16)
     */
    virtual void on_event() {
        TrexStatelessProfile *mprofile = dynamic_cast<TrexStatelessProfile *>(get_port());
        mprofile->change_state(TrexPort::PORT_STATE_STREAMS);
        mprofile->common_profile_stop_actions(true);

        assert(mprofile->m_pending_async_stop_event != TrexDpPortEvents::INVALID_ID);
        mprofile->m_pending_async_stop_event = TrexDpPortEvents::INVALID_ID;
    }

    /**
     * when a DP core encountered an error
     * 
     * @author imarom (20-Apr-16)
     */
    virtual void on_error(int thread_id) {
        Json::Value data;

        TrexStatelessProfile *mprofile = dynamic_cast<TrexStatelessProfile *>(get_port());
        data["port_id"]   = get_port()->get_port_id();
        data["profile_id"]   = mprofile->m_profile_id;
        data["thread_id"] = thread_id;

        get_stateless_obj()->get_publisher()->publish_event(TrexPublisher::EVENT_PORT_ERROR, data);
    }
};
```

Is it cut and past issue?
How could you cast a port to a profile? what do you want to do here?
The event is per port not per profile .. and it wait for all the port to finish

**Comment by hhaim** [comment]
```
    if (profile_id == "*") {
        std::vector<string> profile_list;
        get_profile_id_list(profile_list);

        std::stringstream ss ;
        for (auto &profile_id : profile_list) {
            try {
                TrexStatelessProfile *mprofile = get_profile_by_id(profile_id);
                mprofile->remove_rx_filters();
            } catch (const TrexException &ex) {
                ss << ex.what() << std::endl;
            }
        }

        if (ss.str()!="") {
            throw TrexException(ss.str());
        }

````

I think that we should move the "all profile" to the client. It is duplicate of code in all the functions in CP and DP to support it. 
the server will support one profile-id (or default) and in case of "all-profile" will move to the client in one place "stop/resume/pause-all only need to support it in the client)

**Comment by hhaim** [comment]
> ```
> class AsyncProfileStopEvent : public TrexDpPortEvent {
> 
> protected:
>     /**
>      * when an async event occurs (all cores have reported in)
>      * 
>      * @author imarom (29-Feb-16)
>      */
>     virtual void on_event() {
>         TrexStatelessProfile *mprofile = dynamic_cast<TrexStatelessProfile *>(get_port());
>         mprofile->change_state(TrexPort::PORT_STATE_STREAMS);
>         mprofile->common_profile_stop_actions(true);
> 
>         assert(mprofile->m_pending_async_stop_event != TrexDpPortEvents::INVALID_ID);
>         mprofile->m_pending_async_stop_event = TrexDpPortEvents::INVALID_ID;
>     }
> 
>     /**
>      * when a DP core encountered an error
>      * 
>      * @author imarom (20-Apr-16)
>      */
>     virtual void on_error(int thread_id) {
>         Json::Value data;
> 
>         TrexStatelessProfile *mprofile = dynamic_cast<TrexStatelessProfile *>(get_port());
>         data["port_id"]   = get_port()->get_port_id();
>         data["profile_id"]   = mprofile->m_profile_id;
>         data["thread_id"] = thread_id;
> 
>         get_stateless_obj()->get_publisher()->publish_event(TrexPublisher::EVENT_PORT_ERROR, data);
>     }
> };
> ```
> Is it cut and past issue?
> How could you cast a port to a profile? what do you want to do here?
> The event is per port not per profile .. and it wait for all the port to finish

Ok, I see the logic here.

**Comment by hhaim** [comment]
```
    /* update subscribers */    
    Json::Value data;
    data["port_id"] = m_port_id;
    data["profile_id"] = m_profile_id;
    get_stateless_obj()->get_publisher()->publish_event(TrexPublisher::EVENT_PORT_STARTED, data);
```

There should be an event per port and per profile 
stop on profile id should wait on the event-id. The port the same in case of stop that should be event per profile and per port.

**Comment by hhaim** [comment]
Regarding the events. I think it is not needed to send an async event to the client when profile is changed ((start/stop/ etc) better to send **only** when port is changed (as it was) 

**As a side note**: I think it would be easier to support virtual ports 
As it very strange that profile is derived from **port** in the CP 

and each port has table of profiles that derived from port ..
```
class TrexStatelessProfile: public TrexPort {
```

I don't think it is important to solve this now

**Comment by hhaim** [comment]
> Hi Hanoh,
> 
> I have double check it. In my test environment, we cannot find any failed case.
> Might you test regression with new feature of server only not including Client?
> Please check your configuration.
> 
> If you want to be pull-requested seperately the server of CP and DP to solve regression issue, I will.
> 
> BR,
> Minjae

Did you reconstruct the issue?

**Comment by Cyborn-Minjae-Lee** [comment]
Hi Hanoh,

I just commit one more time.
This commit fixed for regression test issue which you commented.

Please check and give feedback.

BR,
Minjae

**Comment by hhaim** [comment]
The commit look in the right direction to solve the issue.
Could you say why you didn't see the issue (which is very basic) in your regression setup? Is there a problem with out regression?

I will re-run the regression to verify that it works. 

In any case I think that the "all-profile" (*) support should be moved to Python (in a better templating way) so the code would be clear - beter not to integrate the code like this .
It is too many duplications of the interaction on all profiles.

**Comment by hhaim** [comment]
Congratulations. Regression pass on all setups. 
I've reviewed the code  looks good in general, minor comments

* Remove the support for "*" from all the commands RPC/CP (DP does not have this issue)
(Except the necessary cleanup for unit-test and stop_traffic ("all") for shutdown )

for example
```
TrexRpcCmdGetProfileInfo::_run(const Json::Value &params, Json::Value &result) {

  if (profile_id == "*") {
        Json::Value json_profile_stream_list = Json::objectValue;
        std::vector<string> profile_list;
        port->get_profile_id_list(profile_list);

        for (auto &profile_id : profile_list) {
            port->get_id_list(profile_id, stream_list);
            Json::Value json_list = Json::arrayValue;

            for (auto &stream_id : stream_list) {
                json_list.append(stream_id);
            }
            
            std::stringstream ss;
            ss << profile_id;
            json_profile_stream_list[ss.str()] = json_list; 
        }
```
This will be handled in the Python side for remove/stop/resume/pause (all)



* get_port_info
```
if ( get_is_stateless() ) {
        TrexStatelessPort *stl_port = (TrexStatelessPort*) port;
        result["result"]["max_stream_id"] = stl_port->get_max_stream_id();
    }
```
Should add  the information how many profile exits.

* Shouldn't this be profile_id instead of zero 
```
inline void handle(CFlowGenListPerThread *thread) {
        assert(m_state != PCAP_INVALID);
        thread->m_node_gen.m_v_if->send_node( (CGenNode *)this);

        // read the next packet
        next();

        if (is_active()) {
            m_time += get_ipg();
            thread->m_node_gen.m_p_queue.push((CGenNode *)this);  
                            
        } else {
            TrexStatelessDpCore *stl_dp_core = (TrexStatelessDpCore *)thread->get_dp_core();
            stl_dp_core->stop_traffic(get_port_id(), 0, false, 0);  <<<<<<<<<<<<<<<<< HERE <<<<<<<<<<
        }
    }
```

**Comment by Cyborn-Minjae-Lee** [comment]
Hi Hanoh,

I exclued this case in my regression test environment due to failure always.
I  need to reinforce my test environement for test coverage.

I will accept your suggestion for all_profile, get_port_info and commit soon.

BR,
Minjae

**Comment by Cyborn-Minjae-Lee** [comment]
Hi Hanoh,

I will remove get_profile_info in rpc cmd due to aready implementaion in "get_port_status" with additional information "state_profile".

BR,
Minjae

**Comment by jsmoon** [comment]
Hi Haoh,
Let me explain why zero value is used. (stl_dp_core->stop_traffic(get_port_id(), **0**, false, 0);)

The handle method is in CGenNodePCAP structure. It's regarding to push_remote RPC command.
As you mentioned, I made it per port operation, not included in per profile operation.
So, I did not add profile_id in TrexStatelessDpPushPCAP message which is starting PCAP_TX.
Since stopping the PCAP_TX used common stop_traffic() method which has profile_id parameter, I **reserved profile_id 0 as per port operation**.
When stopping PCAP_TX, DP will send TrexDpPortEventMsg with profile_id 0 to make CP can distinguish it from per profile event message.

If you have better idea to deal with it, I will apply it as soon as I possible.

BR,
Jeongseok Moon

**Comment by hhaim** [comment]
Looks good.

**Comment by Cyborn-Minjae-Lee** [comment]
Hi Hanoh,

I'd like to know meging progress for STL Dynamic Profile.
Do you want step by step approach to merging Client including Test and documents after merging Server ?
If not, I will progress Pull-Request for  Client including Test and documents in this branch.

Best Regards,
Minjae

**Comment by hhaim** [comment]
Hi, I’ve tested latest and it pass. 
Seems good to merge.
However because you merge your branch to master it is not possible to rebase it.
It is better that you will do the force rebase to master (using reset HEAD), if not I can do it but your name won’t be on the commit.

Next step, create a client branch and system test commit so we can keep this feature tested

**Comment by Cyborn-Minjae-Lee** [comment]
Hi Hanah,

To clean up merging issue, I will request PR another branch "STL_Dynamic_Profile_Server".

BR,
Minjae

**Comment by hhaim** [comment]
Merged using STL_Dynamic_Profile_Server

**Pull request closed without merging**
