### PR TITLE
limit flow generation by the number of active flows per template

### PR DESCRIPTION
**Pull request by jsmoon**
Hi, this PR is related to #402.

Now, each template can limit the number of active flows.
The number of active flows will be affected by the network situation. The long RTT may increase active flows when the flow program has a long lifetime. This feature can limit the active flows in that situation.

Please check my changes and give your opinion.

### CODE REVIEW

**Comment by hhaim** [comment]
@jsmoon could you rebase on latest? there was an issue at one point that broke the unit-tests

**Comment by hhaim** [comment]
@jsmoon the code looks good

**Comment by egwakim** [comment]
Hi @hhaim ,
Is there any blocker to merge this code into master?

**Comment by hhaim** [comment]
@egwakim will do it today

**Comment by hhaim** [comment]
rebased

**Pull request closed without merging**
