### PR TITLE
Improve reset() routine in ASTFClient API

### PR DESCRIPTION
**Pull request by ejangle**
Optimize current reset() operation in ASTFClient
Changed async mode of stop() and clear_profile() to disable
4000 Profiles reset time : 1148.057001 => 5.909574

### CODE REVIEW

**Comment by ejangle** [comment]
Hi 
Is there any problem with my pull-request issued ?

**Comment by hhaim** [comment]
I’m out of office this week. Will review next week

**Comment by hhaim** [comment]
rebased.

**Comment by hhaim** [comment]
Revert due to stability issues 
see 
https://github.com/cisco-system-traffic-generator/trex-core/pull/362

**Comment by hhaim** [comment]
rebased

**Pull request closed without merging**
