### PR TITLE
ASTF profile regression test cases

### PR DESCRIPTION
**Pull request by JunsubHan4rmEricsson**
@hhaim 
From #299 
ASTF Profile regression test cases have been added for testing

### CODE REVIEW

**Comment by hhaim** [comment]
I’ve run it on all platforms it crash the server

**Comment by JunsubHan4rmEricsson** [comment]
I ran in on the same server I used to test STL.
I only skipped 3 tests(test_topo_zzz_coverage, test_astf_prof_simple_dynamic_profile, test_astf_prof_simple)and passed every other test. 

Could you be more specific with the crash?
Perhaps where in the source it crashed?

**Comment by hhaim** [comment]
I didn’t look. Our DMZ setup should crash too, so you will get the answer soon

**Comment by JunsubHan4rmEricsson** [comment]
Yeah well.
Please let me know more in detail

**Comment by JunsubHan4rmEricsson** [comment]
Hi @hhaim 
I don't see any test cases with errors
However, the test failed with the following reasons. 
Could you please check?

----------------------------------------------------------------------
XML: /tmp/jenkins/unzipped/automation/regression/reports/report_dmz1_stateful.xml
----------------------------------------------------------------------
Ran 33 tests in 2635.720s

OK (SKIP=16)
Skip: The test can't run with following modes of given setup: {'loopback'} 

           /\_/\ 
          ( o.o ) 
           > ^ < 

This cat is sad, test failed.
        

*** python3 test failed

**Comment by JunsubHan4rmEricsson** [comment]
----------------------------------------------------------------------
XML: /tmp/jenkins/unzipped/automation/regression/reports/report_dmz1_stateful.xml
----------------------------------------------------------------------
Ran 33 tests in 2635.720s

OK (SKIP=16)
Skip: The test can't run with following modes of given setup: {'loopback'} 

           /\_/\ 
          ( o.o ) 
           > ^ < 

This cat is sad, test failed.
        

*** python3 test failed

+ STATUS=1
+ cd -
/tmp/jenkins
+ echo Creating HTML report
Creating HTML report
+ cd /tmp/jenkins/unzipped/automation/regression
+ echo dmz1
+ python aggregate_results.py
Processing report: dmz1.stateful
Processing report: dmz1.astf
Processing report: dmz1.stateless
Writing output file: ./reports/aggregated_tests.xml
Writing output file: ./reports/aggregated_tests.html
Writing output file: ./reports/aggregated_tests_mail.html
Writing output file: ./reports/build_status
Writing output file: ./reports/aggregated_tests_title.txt
Status: Failure
+ STATUS=1
+ cp reports/aggregated_tests.html reports/aggregated_tests_mail.html reports/aggregated_tests_title.txt reports/aggregated_tests.xml /tmp/jenkins/reports
+ cd -
/tmp/jenkins
+ set -e
+ [[ 1 != 0 ]]
+ exit 1
+ teardown_func
+ echo Touching reports to update timestamp
Touching reports to update timestamp
+ touch reports/aggregated_tests.html reports/aggregated_tests_mail.html reports/aggregated_tests_title.txt reports/aggregated_tests.xml reports/build.html reports/build.xml reports/report_mail.html reports/report_title.txt
Build step 'Execute shell' marked build as failure
Recording test results
[htmlpublisher] Archiving HTML reports...
[htmlpublisher] Archiving at BUILD level /tmp/jenkins/reports to /var/lib/jenkins/jobs/trex_build/builds/128/htmlreports/HTML_20Report
Setting status of 11364bb1444b480dbb8e4d3d0cb9ac41f66ff475 to FAILURE with url  and message: 'Build finished. '
FileNotFoundException means that the credentials Jenkins is using is probably wrong. Or the user account does not have write access to the repo.
org.kohsuke.github.GHFileNotFoundException: {"message":"Not Found","documentation_url":"https://developer.github.com/v3/repos/statuses/#create-a-status"}
	at org.kohsuke.github.Requester.handleApiError(Requester.java:699)
	at org.kohsuke.github.Requester._to(Requester.java:306)
	at org.kohsuke.github.Requester.to(Requester.java:247)
	at org.kohsuke.github.GHRepository.createCommitStatus(GHRepository.java:1104)
	at org.jenkinsci.plugins.ghprb.extensions.status.GhprbSimpleStatus.createCommitStatus(GhprbSimpleStatus.java:283)
	at org.jenkinsci.plugins.ghprb.extensions.status.GhprbSimpleStatus.onBuildComplete(GhprbSimpleStatus.java:241)
	at org.jenkinsci.plugins.ghprb.GhprbBuilds.onCompleted(GhprbBuilds.java:205)
	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onCompleted(GhprbBuildListener.java:28)
	at hudson.model.listeners.RunListener.fireCompleted(RunListener.java:209)
	at hudson.model.Run.execute(Run.java:1863)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Caused by: java.io.FileNotFoundException: https://api.github.com/repos/cisco-system-traffic-generator/trex-core/statuses/11364bb1444b480dbb8e4d3d0cb9ac41f66ff475
	at sun.reflect.GeneratedConstructorAccessor161.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1944)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1939)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1938)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1508)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
	at org.kohsuke.github.Requester.parse(Requester.java:625)
	at org.kohsuke.github.Requester.parse(Requester.java:607)
	at org.kohsuke.github.Requester._to(Requester.java:285)
	... 11 more
Caused by: java.io.FileNotFoundException: https://api.github.com/repos/cisco-system-traffic-generator/trex-core/statuses/11364bb1444b480dbb8e4d3d0cb9ac41f66ff475
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1890)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:347)
	at org.kohsuke.github.Requester.parse(Requester.java:615)
	... 13 more
Checked SHA: 11364bb1444b480dbb8e4d3d0cb9ac41f66ff475
Status: **FAILURE** :x:
Link to job: http://81.218.86.50:8080/job/trex_build/128/

Finished: FAILURE

**Comment by hhaim** [comment]
@JunsubHan4rmEricsson 

It would be nice to have a more random/stress test that works with events  

Something like this was done for STL multi profile 
 https://github.com/cisco-system-traffic-generator/trex-core/commit/989bc0a88ce38ab94903c49c496d89f58822461a#diff-215c7dd05e1e2b4fa6dfc7542ef2ead4

**Comment by JunsubHan4rmEricsson** [comment]
> @JunsubHan4rmEricsson
> 
> It would be nice to have a more random/stress test that works with events
> 
> Something like this was done for STL multi profile
> [989bc0a#diff-215c7dd05e1e2b4fa6dfc7542ef2ead4](https://github.com/cisco-system-traffic-generator/trex-core/commit/989bc0a88ce38ab94903c49c496d89f58822461a#diff-215c7dd05e1e2b4fa6dfc7542ef2ead4)

Will do
I will get to it tomorrow
But what do you think about the tests so far?

**Comment by hhaim** [comment]
@JunsubHan4rmEricsson 

Could you reduce the total time of the dynamic tests  
Your tests take x2 of the total time of ASTF suite 
see list 
http://81.218.86.50:8080/job/trex_build/129/testReport/(root)/dmz1/

```Took 1 hr 57 min.```

**Comment by JunsubHan4rmEricsson** [comment]
Hi Hanoh,
In addition to reducing the test time, I've also added another random stress test similar to 989bc0a#diff-215c7dd05e1e2b4fa6dfc7542ef2ead4

**Comment by JunsubHan4rmEricsson** [comment]
@hhaim 
Please check the test cases for me
Thanks.

**Comment by hhaim** [comment]
The tests look good. The time is reasonable now. 
Will try to merge to master.

**Comment by hhaim** [comment]
There are a few issues that have been fixed please review. 
https://github.com/hhaim/trex-core/tree/astf_regression1

1) Out of memory crash in low end platform, need to differentiate the test for low/high end platform 
2) You merge and override the master code 

now even after the fix there is a no stable test

```
ERROR
----------------------------------------------------------------------
XML: /auto/srg-sce-swinfra-usr/emb/users/hhaim/work/depot/asr1k/emb/private/hhaim/bp_sim_git/trex-core/scripts/automation/regression/reports/report_trex03_astf.xml

-----------------------------------------------------------------------------
1) ERROR: test_astf_template_group_edge_cases_dynamic_profile (astf_tests.astf_template_group_test.ASTFTemplateGroup_Test)

   Traceback (most recent call last):
    astf_tests/astf_template_group_test.py line 364 in test_astf_template_group_edge_cases_dynamic_profile
      self.c.clear_stats(pid_input=str(random_profile))
    /auto/srg-sce-swinfra-usr/emb/users/hhaim/work/depot/asr1k/emb/private/hhaim/bp_sim_git/trex-core/scripts/automation/trex_control_plane/interactive/trex/common/trex_api_annotators.py line 51 in wrap2
      ret = f(*args, **kwargs)
    /auto/srg-sce-swinfra-usr/emb/users/hhaim/work/depot/asr1k/emb/private/hhaim/bp_sim_git/trex-core/scripts/automation/trex_control_plane/interactive/trex/astf/trex_astf_client.py line 781 in clear_stats
      valid_pids = self.validate_profile_id_input(pid_input)
    /auto/srg-sce-swinfra-usr/emb/users/hhaim/work/depot/asr1k/emb/private/hhaim/bp_sim_git/trex-core/scripts/automation/trex_control_plane/interactive/trex/astf/trex_astf_client.py line 239 in validate_profile_id_input
      raise TRexError("ASTF profile_id %s does not exist." % profile_id)
   TRexError: ASTF profile_id timjdbaksm does not exist.


-----------------------------------------------------------------------------
2 tests run in 4.8 seconds. 
1 error (1 test passed)

           /\_/\ 

```

I've disabled it for now

**Comment by hhaim** [comment]
Can we close this?

**Pull request closed without merging**
