### PR TITLE
Fix garbage info in multiple ASTFProfile

### PR DESCRIPTION
**Pull request by egwakim**
Issue #328 : Fix garbage info when multiple ASTFProfile creation

### CODE REVIEW

**Comment by egwakim** [comment]
Regression failed, but, it seems issue in testing environment.
Can you check the issue?

**Comment by hhaim** [comment]
It is not related to testing environment. It relates to template group.
I would look into the specific test to understand why this patch does not work in this case

**Comment by hhaim** [comment]
The issue is that the cache (buffers) is static. I think it is better to make it per object

**Comment by egwakim** [comment]
Current ASTF programming model is not designed as per object.
ASTFProfile using cached ASTFProgram, ASTFIPGen, ASTFTemplate.
To be able to support both existing test case which using cached ASTFProfile and cleaning up cached old profile, it's better clean-up multi-profile only.


       profile_json = profile.to_json_str(pretty = False, sort_keys = True)
+        if pid_input != DEFAULT_PROFILE_ID :
+            profile.clear_cache()

        self.ctx.logger.pre_cmd('Loading traffic at acquired ports.')

**Comment by hhaim** [comment]
@egwakim I think it is better to make the cache per object and not global (static)
Your suggestion will work too, but it is a bypass to test case that test only DEFAULT_PROFILE_ID
This test case won't work with multi-profiles without changing the global to per object

**Comment by ybrustin** [comment]
Per-object (and with this PR as well) the cache will not be shared with new profiles.
Each "start" from console, for example, will parse all the pcaps again.

I would suggest to add some sort of TTL to cache entries.
Entry is not used for N profiles => remove it.

**Comment by hhaim** [comment]
It is not about reading the pcap file. it is about the the cache of program/buffers/generators
it should be per profile and not global as in current implementation

**Comment by egwakim** [comment]
We can change class variables(ASTFIPGenDist.in_list, _ASTFTemplateBase.program_list, _ASTFTemplateBase.program_hash) into instance variables.
Then, we do not need to explicitly call clear_cache() because these will be part of object.

But, per-object will cause issues on many test cases because current test case is written by cached assumption. We need to change all these test cases. These test cases re-using templates after load_profiles. That's the issue.

Another option is adding explicit option in load_profile(clear_profile).
clear_profile : default = false, clear profile after load if it's true.
It's similar to first option(Let user to explicit call ASTFProfile.clear_cache() before generate profile).

**Comment by hhaim** [comment]
Could you provide an example for this one?

> But, per-object will cause issues on many test cases because current test case is written by cached assumption. We need to change all these test cases. These test cases re-using templates after load_profiles. That's the issue.
> 

I think that the right solution is to keep the cache per profile (this was the design not sure from where come the global stuff). Explicitly clear of the cache does not make sense. The user doesn't care about our  internal optimization. 

I didn't notice this global cache and it seems to me as a big problem that should be fixed.

**Comment by egwakim** [comment]
astf_template_group_test reuses ipgen object in 2 ASTFProfiles and called load_profile() twice.
I rechecked test case code, it'll not the issue because ipgen object will not be removed by Python GC, it's referenced by other objects. No issue after per-object change.

per-object requires quite a lot change on  trex_astf_profile codes because these are written for classmethod. Converting json code need to be changed and buf_list in ASTFIPGenDist,ASTFProgm ASTFTemplate need to be handled via object method.
And we need to remove all these classmethod after per-object change.

I need to discuss this topic with my team for the priority because it'll need some efforts for the proper change and we have workaround(calling clear_cache).

Best Regards
Gwangmoon

**Comment by egwakim** [comment]
After discussion, we decided to postpone it because most of users are using Java APIs and there is workaround solution of it. It's not the urgent issue.
Change to per-object approach is proper solution.

Regards
Gwangmoon

**Pull request closed without merging**
