### PR TITLE
add sched_max_stretch configuration for #538

### PR DESCRIPTION
**Pull request by jsmoon**
@hhaim this PR is for #538 discussion.
New "get_global_cfg" and "set_global_cfg" RPC commands are added.

Please check my changes and give your feedback.

### CODE REVIEW

**Comment by hhaim** [comment]
@jsmoon almost

1. 

This original code 
```
 while (state!=scTERMINATE) {

         switch (state) {
         case scINIT:
            cur_time = now_sec();
            {
                dsec_t dt = cur_time - n_time ;

                if (dt > BURST_OFFSET_DTIME) {
                    state = scSTRECH;
                } else if (dt > 0) {
                    state = scWORK;
                } else {
                    state = scWAIT;
                }

            }

```

should be replaced to be 

```
 while (state!=scTERMINATE) {

         switch (state) {
         case scINIT:
            cur_time = now_sec();
            {
                dsec_t dt = cur_time - n_time ;

                if (dt > **m_burst_size**)  {  <<<<<<<<<<<<<<<<<<<
                    state = scSTRECH;
                } else if (dt > 0) {
                    state = scWORK;
                } else {
                    state = scWAIT;
                }

            }

```


Your change in ```handle_time_strech``` is not good, as in the scheduler ```   if (dt > BURST_OFFSET_DTIME) {``` this will be true, it will get to ```handle_time_strech``` and it will do nothing, it will be a waste of loops to get in and out of STRECH state without doing anything 

 it is better **not** to get to it at all (and remove this function change )

```
oid CNodeGenerator::handle_time_strech(CGenNode * &node,
                                        dsec_t &cur_time,
                                        dsec_t &n_time,
                                        dsec_t &offset,
                                        CFlowGenListPerThread *thread) {
```



2. Update the help string 

```
    def set_global_cfg (self, params):
        """
            Change global configuration parameters.

            :parameters:
                params: dictionary
                    dictionary of global configuration parameters. Available parameters:


                    "sched_max_stretch", type = double, default =0.0, units = usec, scheduler's maximum time for stretch in case it is a high value there won't be a scheduler compensation on burst and time will not be stretch. 0.0 means use the default internal value (~100usec). value could not be lower than 100usec will be considered as 100usec. 

            :raises:
                + :exc:`TRexError`

        """
```
2. We should not set ```m_burst_offset_dtime``` smaller than  BURST_OFFSET_DTIME (~ 100usec )
else the scheduler will be very **not efficient** 

```
   #define BURST_OFFSET_DTIME    (100.0/1000000)
```

so this code should protect against too very low value s 

```
    if (CGlobalInfo::m_burst_offset_dtime > 1.0 ) {
        if (CGlobalInfo::m_options.preview.getVMode() > 3) {
            std::cout << "burst_size = " << m_burst_size << std::endl;
        }
          m_burst_size = BURST_OFFSET_DTIME;

       if CGlobalInfo::m_burst_offset_dtime>BURST_OFFSET_DTIME {
          m_burst_size = CGlobalInfo::m_burst_offset_dtime;
       }
}

```

**Comment by jsmoon** [comment]
1. `handle_time_strech` performs additional `handle_maintenance` to prevent watchdog. So, if `m_burst_size` is large, it may cause watchdog.
2. I'll apply it.
3. Since the `handle_time_strech` is performed only when `dt > BURST_OFFSET_DTIME`, too low value is protected implicitly.

**Comment by hhaim** [comment]
@jsmoon understood, we have been mixing two things what about this?

```            

..
            cur_time = now_sec();
            {
                dsec_t dt = cur_time - n_time ;

                // real time clock  (not streched)
                dsec_t dtr = cur_time - m_last_sync_time_sec ;
                if ( dtr > SYNC_TIME_OUT){
                    handle_maintenance_job()
                }

                if (dt > m_burst_size ) {
                    state = scSTRECH;
                } else if (dt > 0) {
                    state = scWORK;
                } else {
                    state = scWAIT;
                }
            }



handle_maintenance_job() {
                    handle_maintenance(thread);
                    node = m_p_queue.top();
                   n_time = node->m_time + offset;

}


```

The problem with your patch that in case you go to ```handle_time_strech ``` and **not** fixing the time_offset, you will get to this function again and again (every 15usec) without doing anything,

This way we disconnect the relation between stretching the time and watchdog handling 


and ```handle_time_strech ``` will do only explicit stretch and not watchdog 

```
void CNodeGenerator::handle_time_strech(CGenNode * &node,
                                        dsec_t &cur_time,
                                        dsec_t &n_time,
                                        dsec_t &offset,
                                        CFlowGenListPerThread *thread) {


    /* fix the time offset */
    dsec_t dt = cur_time - n_time;
    offset += dt;
    /* set new offset */
    m_scheduler_offset = offset;
}
```

**Comment by hhaim** [comment]
@jsmoon, looks good. 
thanks

**Comment by hhaim** [comment]
rebased.

**Pull request closed without merging**
