### PR TITLE
From STL_Profile_Regression_Test_Refinement for travis regressiont test

### PR DESCRIPTION
**Pull request by JunsubHan4rmEricsson**
Merged from #224 for travis regression test

### CODE REVIEW

**Comment by hhaim** [comment]
see results here
https://github.com/cisco-system-traffic-generator/trex-core/pull/264

**Comment by JunsubHan4rmEricsson** [comment]
I think the problem was due to such high PPS for 100 profiles. 
I've decreased the PPS for test cases, 
**1) test_pause_resume_update_dynamic_profile
2) test_pause_resume_update_streams**

**Comment by JunsubHan4rmEricsson** [comment]
2d26abc should be disregarded by the way.
I've made more commits afterwards

**Comment by JunsubHan4rmEricsson** [comment]
Hi Hanoh, 
About the regression failure on 76e2842 on trex08, 
You have previously mentioned that 

**trex-08 does not work (XL710) while trex-09 (X710) works.
it might be related to the fact that trex-08 is connected like this

0->3
1->2
2->1
3->0

Instead of (trex-09)

0->1
1->0
2->3
2->2

This has more race conditions than the normal when one core handles both 0,1 2,3**

What do you suggest from our side now?
It seems that every other error has been fixed.

**Comment by hhaim** [comment]
> Hi Hanoh,
> About the regression failure on [76e2842](https://github.com/cisco-system-traffic-generator/trex-core/commit/76e2842535af0d9d638ac8d5b8a9405abe70de89) on trex08,
> You have previously mentioned that
> 
> > trex-08 does not work (XL710) while trex-09 (X710) works.
> > it might be related to the fact that trex-08 is connected like this
> > 0->3
> > 1->2
> > 2->1
> > 3->0
> > Instead of (trex-09)
> > 0->1
> > 1->0
> > 2->3
> > 2->2
> > This has more race conditions than the normal when one core handles both 0,1 2,3
> 
> What do you suggest from our side now?
> It seems that every other error has been fixed.

Could you elaborate? I don't understand the question.
I've suggested more than on time to build setup like trex-08 in your place (add one card) and find the issue and fix it locally. our regression  setup is only to find issues that related to esoteric setups not for the main stream, simple setup

**Comment by JunsubHan4rmEricsson** [comment]
First, **test_pause_resume_update_dynamic_profile** test case has been fixed.
This is the one that occurred in most of regression setups

Two errors that seem to take place continuously **alternatively** in travis and travis only, not ours.
**1) test_latency_pause_resume_dynamic_profile (takes place only in trex08 setup)**
AssertionError: Port 0 : *** For payload rules: Can't have two streams with same pg_id, or same stream on more than one port

**2) test_pause_resume_update_streams (takes place only in trex19 setup)**
AssertionError: expected TX ~200pps, got: 92.4

Neither of these errors take place in our environment (which is set up exactly like trex 08 of yours)
Here's the setup I'm using for regression. 
**08:00.0 Ethernet controller: Intel Corporation Ethernet Controller XL710 for 40GbE QSFP+ (rev 02)
08:00.1 Ethernet controller: Intel Corporation Ethernet Controller XL710 for 40GbE QSFP+ (rev 02)**

As mentioned, the two test cases do not occur in my environment. 

Now, 
For **1) test_latency_pause_resume_dynamic_profile**, you have mentioned the following.
This is what you said before. 
> trex-08 does not work (XL710) while trex-09 (X710) works.
> it might be related to the fact that trex-08 is connected like this
> 
> 0->3
> 1->2
> 2->1
> 3->0
> 
> Instead of (trex-09)
> 
> 0->1
> 1->0
> 2->3
> 2->2
> 
> This has more race conditions than the normal when one core handles both 0,1 2,3
I'm not exactly sure what you mean with this. 
But you seem to have a clue about why this fails. 
So, my question is. 
What do you suggest that I do?
and what exactly do you mean by what yous said before? 
0->3, 1->2...what do you mean and how do you think it affects the pg_id error?

For **2) test_pause_resume_update_streams**, I did not implement this test case myself.
There seems to be a problem with a performance issue for the following reasons.
1) It only takes place in trex19 only
2) The problem is with the shortage of TX (ex, expected TX ~1200pps, got: 1006.8)
Does this test case pass all the time?
Or do you think that this test case (which I didn't write) is failing because of our recent implementation?

Does it make sense?

**Comment by hhaim** [comment]
1) When the core that Tx the traffic redirect the traffic to different core there are usually new race condition in the code. This is why we loopback trex-08 in this way.  I suggest to connect the loppback like we do and reconstruct and understand the issue
2) The regression without this PR works fine on all the setups . I would look for the reason for 1 first maybe it is related issues.

**Comment by JunsubHan4rmEricsson** [comment]
Hanoh, what's etc/trex_cfg.yaml for the system (trex08)?

**Pull request closed without merging**
