### PR TITLE
Enable limit-memory without --prefix in config file

### PR DESCRIPTION
**Pull request by Cyborn-Minjae-Lee**
Hi Hanoh,

I would like to PR for this feature which enable an option "--limit-memory" without "--prefix".
Until now, If run TRex without prefix, all of hugepages are depleted although "--limit_memory" is set in config file.

@egwakim @ejaecki @Kangphil @yonghwan007 @jsmoon @JunsubHan4rmEricsson @youngjun1 @Cyborn-Minjae-Lee 

Best Regards,
Minjae Lee

### CODE REVIEW

**Comment by Cyborn-Minjae-Lee** [comment]
I have reinforced the condition for an option "limit-memory".

**Comment by Cyborn-Minjae-Lee** [comment]
Hi,

Is there any considering this PR?

**Comment by hhaim** [comment]
Yes, look good will be committed

**Comment by hhaim** [comment]
rebased

**Pull request closed without merging**
