### PR TITLE
ASTF dynamic profile regression test updated

### PR DESCRIPTION
**Pull request by JunsubHan4rmEricsson**
@hhaim 
Referencing #304 for merge

### CODE REVIEW

**Comment by JunsubHan4rmEricsson** [comment]
An error has taken place in a test case which I didn't change.
Are you familiar with this? **test_performance_vm_multi_cpus_cached
**

**Comment by hhaim** [comment]
It is probably false

**Comment by JunsubHan4rmEricsson** [comment]
Will this be merged then?

**Comment by hhaim** [comment]
Yes

**Pull request merged**
