### PR TITLE
added  back the test case

### PR DESCRIPTION
**Pull request by JunsubHan4rmEricsson**
Hi @hhaim 
This test case should be added back since #355 has been solved. 
It passes regression test from our side. 
Please check it for me.

### CODE REVIEW

**Comment by hhaim** [comment]
@JunsubHan4rmEricsson, It seems that I have missed this.

**Comment by JunsubHan4rmEricsson** [comment]
@hhaim we excluded this test case because #355 was not implemented before (which solves issues that existed in #304 with the test case)

**Comment by JunsubHan4rmEricsson** [comment]
@hhaim let me know if any changes need to be made for this PR

**Comment by hhaim** [comment]
rebased

**Pull request closed without merging**
