### PR TITLE
ASTF prevents new server flow after stopped

### PR DESCRIPTION
**Pull request by jsmoon**
Hi, I had met a crash case due to a flow with a removed profile.
I found the reason and this PR would fix it.

@hhaim, please check my change and give your feedback.

### CODE REVIEW

**Comment by hhaim** [comment]
@jsmoon please rebase on latest master

**Comment by jsmoon** [comment]
Hi, my original PR causes side effects when a profile runs on multiple cores.
I missed the graceful-stop by the duration should keep the server flow generation after stopped because other core clients can be generating new flows.
So, I changed this PR to clean up unexpected server flows.
Since the unexpected flows would rarely happen by abnormal packets, I think this change has no impact on the normal situation.
@hhaim, please check my changes again and give your feedback.

**Comment by hhaim** [comment]
@jsmoon you can't iterate over all the flows, you could have 100Mflows. Add a tag to each flow 

This will trigger a WD 
```
int CCloseHash<KEY>::detach_if(void *userdata,
                                 close_hash_on_detach_cb_t cb, void *pdata, close_hash_predicate_cb_t p){
    int detach_cnt = 0;

    for(int i=0;i<m_size;i++){
        CCloseHashRec * lpRec= &m_tbl[i];
        TCGenDListIterator iter(lpRec->m_list);
        hashEntry_t *lp;
        int f_itr=0;
        for (;(lp=(hashEntry_t *)iter.node());){
            iter++;
            if (p(pdata, lp)){
                lp->detach();
                m_numEntries--;
                cb(userdata,(void *)lp);
                detach_cnt++;
            }
            f_itr++;
        }
    }

    return detach_cnt;
}
```

**Comment by jsmoon** [comment]
@hhaim I have no idea how the tag on each flow can help to find flows of a specific profile faster.
Could you elaborate on the idea?

**Comment by jsmoon** [comment]
@hhaim I added a flow list for surplus flows created after the profile stopped.
Since the number of surplus flows is small, I think the impact would be negligible.

**Comment by hhaim** [comment]
@jsmoon it is not fundamentally better. Why you are adding the flow if the profile_ctx is not active from the first place?
Iterating over flows is not a good idea especially this code that liniary iterate to find one flow. to remove ```n``` flow  it would be ```n^2```

```
void remove_flow(CFlowBase* flow) {
        m_flow_cnt--;
        if (!is_active()) {
            auto it = find(m_flows.begin(), m_flows.end(), flow);
            if (it != m_flows.end()) {
                m_flows.erase(it);
            }
        }
    }
```

Could you describe your issue again? 
My idea with the tag is to add some tag information that you could by fast query know if this flow is associated with active profile. 
them let the flow age out and kill it if the tag related to inactive profile context. 
Doing a big batch of work is not recommended

**Comment by jsmoon** [comment]
@hhaim let me explain this issue at first.
The crash issue occurred by the flow which was generated after a DP core report finished TX to CP.
It can happen only from the *extra abnormal packets*.
ASTF server program already closed the open flow and reported the profile finished but a cleanup request from CP not yet delivered. During this period, a new packet can make a new flow to the *inactive* profile.
If the packet is *normal* from the other DP core client, the cleanup request would hold until regarding client flow is closed. This is normal.
But if the packet is *abnormal* from an unknown source, CP requests to cleanup profile to DP core, and the flow is left after the profile's AstfDB instance removed. *This flow causes crashes.*

As I mentioned before, the number of surplus flows would be small. So I think the linear search would be enough.
If you worried about the linear search, I can change it to binary search using `std::set`.
Please let me know what you want.

**Comment by jsmoon** [comment]
@hhaim, I changed the linear search to binary search using `std::set`.

> Doing a big batch of work is not recommended

The surplus flows are small and it's not a big batch.

> My idea with the tag is to add some tag information that you could by fast query know if this flow is associated with active profile.
them let the flow age out and kill it if the tag related to inactive profile context.

To add the tag to the flow, the profile should find the flow at first. I don't know how the tag gets a benefit in this situation.

**Comment by hhaim** [comment]
@jsmoon one question, why to open a flow from the first place in this situation. You are opening the flow and add them to a list and then close them. in this state (profile_ctx is not active) just don't open the flows.

**Comment by jsmoon** [comment]
@hhaim my first PR(cb75ede) has been done as you said. But the regression test was failed. Please see [my comment](https://github.com/cisco-system-traffic-generator/trex-core/pull/618#issuecomment-772326670) about it.

**Comment by jsmoon** [comment]
PR #625 would be a better solution. I'll give up this change.

**Pull request closed without merging**
