### PR TITLE
Documentation for GTP tunnel

### PR DESCRIPTION
**Pull request by vineetbvp**

### CODE REVIEW

**Comment by hhaim** [comment]
@vineetbvp very good. 

minor comments:

* There is a limitation that you can use only 2 ports and only port 0 (client side) can be configured as GTPU tunnel. worth adding this. 
* Worth to give a full example with client_cluster cfg file that add the tunnels (without the API)  and not just the API so user would be able to *experiment* the new feature using a simple commands from the Console and not a script. 
* It worth adding a simple script that add the tunnels and start the traffic as a reference  
*

**Comment by vineetbvp** [comment]
regarding this comment:
Worth to give a full example with client_cluster cfg file that add the tunnels (without the API) and not just the API so user would be able to experiment the new feature using a simple commands from the Console and not a script.

Our trex team will be  working on Topomgr(configured clients) which you had suggested.
That time they will add the documentation

**Comment by hhaim** [comment]
@vineetbvp you are right, I forgot that you have added only the API. In that case it is better to add a simple console a command to add/remove a tunnel using the API and add it to the tutorial. 
This should be simple to add, could you do it?

**Comment by jsmoon** [comment]
@vineetbvp and @hhaim, in my test, this feature doesn't work.
Could you check it functional before documentation?

**Comment by hhaim** [comment]
@jsmoon the feature works for them. @vineetbvp is no longer working on this. The documentation is not final and it wasn't released yet. The missing part is that there is no Console simple tutorial to test it (the API to add/remove client tunnel is not exposed as a command).

**Comment by jsmoon** [comment]
@hhaim this feature doesn't work with the latest DPDK 21.02 update.
please check my simple fix for them.
```
diff --git a/src/44bsd/tcp_output.cpp b/src/44bsd/tcp_output.cpp
index ae68779e..73c71a7b 100644
--- a/src/44bsd/tcp_output.cpp
+++ b/src/44bsd/tcp_output.cpp
@@ -184,7 +184,7 @@ static inline int _tcp_build_cpkt(CPerProfileCtx * pctx,
         if (!ftp->is_tunnel_aware() && ctx->is_client_side()){
            INC_STAT(pctx, tp->m_flow->m_tg_id, tcps_notunnel);
         }
-        pkt.m_buf->dynfield1[0] = (uint64_t)ftp->m_tun_handle;
+        pkt.m_buf->dynfield_ptr = ftp->m_tun_handle;
      }
 
     if (m==0) {
diff --git a/src/44bsd/udp.cpp b/src/44bsd/udp.cpp
index d70b6ebc..1d3e9100 100644
--- a/src/44bsd/udp.cpp
+++ b/src/44bsd/udp.cpp
@@ -84,7 +84,7 @@ HOT_FUNC void CUdpFlow::update_checksum_and_lenght(CFlowTemplate *ftp,
         if (!ftp->is_tunnel_aware() && m_pctx->m_ctx->is_client_side()){
             INC_UDP_STAT(m_pctx, m_tg_id, udps_notunnel);
         }
-        m->dynfield1[0] = (uint64_t)ftp->m_tun_handle;
+        m->dynfield_ptr = ftp->m_tun_handle;
     }
     if (ftp->m_offload_flags & OFFLOAD_TX_CHKSUM) {
         if (!ftp->m_is_ipv6) {
diff --git a/src/tunnels/gtp_tunnel.cpp b/src/tunnels/gtp_tunnel.cpp
index cf24e2d1..b49a2691 100644
--- a/src/tunnels/gtp_tunnel.cpp
+++ b/src/tunnels/gtp_tunnel.cpp
@@ -138,7 +138,7 @@ int GTPU::Prepend_ipv4_tunnel(rte_mbuf * pkt, u_int8_t l3_offset, u_int16_t queu
     rte_ether_addr_copy(&eth->s_addr, &outer_eth->s_addr);
     rte_ether_addr_copy(&eth->d_addr, &outer_eth->d_addr);
 
-    struct rte_ipv4_hdr * outer_ipv4 = (struct rte_ipv4_hdr *)(eth+1);
+    struct rte_ipv4_hdr * outer_ipv4 = (struct rte_ipv4_hdr *)(outer_eth+1);
 
     if (eth->ether_type == kEtherTypeBeVLAN) {
 
@@ -201,7 +201,7 @@ int GTPU::Prepend_ipv6_tunnel(rte_mbuf * pkt, u_int8_t l3_offset, u_int16_t queu
     struct rte_ether_hdr * outer_eth = (struct rte_ether_hdr *)encap6;
     rte_ether_addr_copy(&eth->s_addr, &outer_eth->s_addr);
     rte_ether_addr_copy(&eth->d_addr, &outer_eth->d_addr);
-    struct rte_ipv6_hdr * outer_ipv6 = (struct rte_ipv6_hdr *)(eth+1);
+    struct rte_ipv6_hdr * outer_ipv6 = (struct rte_ipv6_hdr *)(outer_eth+1);
     outer_eth->ether_type = eth->ether_type;
 
     if (eth->ether_type == kEtherTypeBeVLAN) {
```

**Comment by hhaim** [comment]
@jsmoon v2.88 incorporates your fixes

**Pull request closed without merging**
