### PR TITLE
fixed the push -r stop error

### PR DESCRIPTION
**Pull request by JunsubHan4rmEricsson**
Regarding #285 
@ybrustin @hhaim 
Please try it and provide feedback

### CODE REVIEW

**Comment by JunsubHan4rmEricsson** [comment]
@hhaim 
Have you checked this PR?
Let me know if you find any problems with it

**Comment by jsmoon** [comment]
I've found the port state is transmitting after push -r finished.
The commit 1dd6757 will fix this issue.

**Comment by JunsubHan4rmEricsson** [comment]
@hhaim Have you tried the fixed version?

**Comment by hhaim** [comment]
rebased

**Pull request closed without merging**
