### PR TITLE
-a option added for stop command (remove all profiles * when -a is used)

### PR DESCRIPTION
**Pull request by JunsubHan4rmEricsson**
Following form #239.
No source has been changed from #239.
Just rebased the master to test travis.

### CODE REVIEW

**Comment by elados93** [comment]
Your pull request passed, ignore travis.
You can download the results [here](https://drive.google.com/uc?id=1x9e19JLVIfYUosq_T7lmTwSZ4ccVwdof&export=download) as _html_ file

**Comment by JunsubHan4rmEricsson** [comment]
Sounds wonderful.
So then this will be merged, correct?

**Comment by hhaim** [comment]
Yes, it seems we still have an issue in our internal job.
The report will look the same, but with the right SHA..
The merge will be done manually  .

**Comment by hhaim** [comment]
rebased.

**Pull request closed without merging**
