### PR TITLE
API to update tunnel information for clients

### PR DESCRIPTION
**Pull request by vineetbvp**
1.  If tunnel info is not present, add it else update
2.  Little refactor GTP code
3.  New files tunnel_factory_creator.*
Fix for generate flow incase of shared clients for among client pools

### CODE REVIEW

**Comment by hhaim** [comment]
@vineetbvp looks good. Could you add a small documentation in ASTF manual for how to use it and the limitation

**Comment by vineetbvp** [comment]
> @vineetbvp looks good. Could you add a small documentation in ASTF manual for how to use it and the limitation

@hhaim 
Can you send me the steps how to add the manual ?

**Comment by hhaim** [comment]
@vineetbvp just add a new section, in asciidoc format 
https://github.com/cisco-system-traffic-generator/trex-core/blob/master/doc/trex_astf.asciidoc

add it as a tutorial after this section
https://trex-tgn.cisco.com/trex/doc/trex_astf.html#_tutorial_server_port_sharing_between_templates

and add a profile as an example

**Comment by hhaim** [comment]
rebased

**Pull request closed without merging**
