### PR TITLE
for more accurate estimation of tsc frequency in x86.

### PR DESCRIPTION
**Pull request by jsmoon**
Hi, this PR is a change for #634.

@hhaim please review my change.

### CODE REVIEW

**Comment by jsmoon** [comment]
@hhaim the test failure is due to connection timeout. Could you check it?
```
  File "/usr/lib64/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

*** python3 test failed
```

**Comment by hhaim** [comment]
@jsmoon will have a look

**Comment by hhaim** [comment]
recheck

**Comment by ybrustin** [comment]
recheck

**Comment by hhaim** [comment]
rebased

**Pull request closed without merging**
