### PR TITLE
Uplift TCP/IP stack (FreeBSD 13 based)

### PR DESCRIPTION
**Pull request by jsmoon**
This PR is related to #759.

This change replaces the old 4.4BSD TCP/IP stack with the new FreeBSD 13 TCP/IP stack.
The new stack supports SACK and the new CC algorithm(newreno and CUBIC).

@hhaim please give your feedback on this change.

### CODE REVIEW

**Comment by hhaim** [comment]
@jsmoon 

It is still under review, I running full regression. In general it looks very good! 


**few comments**: 

1) you are writing data into the **mbuf packets** which is share data with PCI/other cores and could create false sharing
instead it is better to make a copy in the stack and convert it 

```
static inline void
tcp_fields_to_host(struct tcphdr *th)
{
	th->th_seq = ntohl(th->th_seq);
	th->th_ack = ntohl(th->th_ack);
	th->th_win = ntohs(th->th_win);
	th->th_urp = ntohs(th->th_urp);
}

instead:
	tcp_fields_to_host(th);
```

```
struct tcphdr *th_pkt

// in the stack -- fast in the cache 
struct tcphdr th

convert_to_host(th,th_pkt){
    th->flags =th_pkt->flags 
	th->th_seq = ntohl(th_pkt->th_seq);
	th->th_ack = ntohl(th_pkt->th_ack);
	th->th_win = ntohs(th_pkt->th_win);
	th->th_urp = ntohs(th_pkt->th_urp);
    .. all the fields
}
   ```



2) 
	you don't have this sanity check to drop the packet !, it could create a crash 

```
    if (l7off + ti->ti_len > m->pkt_len )){
        /* somthing wrong here drop the packet */
        goto drop;
    }


```


3) our regression fail with gcc 7 I need to do this

```
diff --git a/linux_dpdk/ws_main.py b/linux_dpdk/ws_main.py
index 13de4f296..864dd92d8 100755
--- a/linux_dpdk/ws_main.py
+++ b/linux_dpdk/ws_main.py
@@ -2510,11 +2510,13 @@ def build_prog (bld, build_obj):
               source   = bpf.file_list(top),
               target   = build_obj.get_bpf_target())
 
-    bld.stlib(features = 'c',
-              includes = tcp_includes_path,
-              cflags   = cflags,
-              source   = tcp_src.file_list(top),
-              target   = build_obj.get_tcp_target())
+    bld.objects(
+      features='c ',
+      includes = tcp_includes_path,
+      cflags   = cflags,
+      source   = tcp_src.file_list(top),
+      target=build_obj.get_tcp_target()
+      )
 
     inc_path = dpdk_includes_path + includes_path
     cxxflags_ext = ['',]
diff --git a/src/44bsd/netinet/tcp_timer.c b/src/44bsd/netinet/tcp_timer.c
index e3fa9ce79..86138ea1b 100644
--- a/src/44bsd/netinet/tcp_timer.c
+++ b/src/44bsd/netinet/tcp_timer.c
@@ -340,8 +340,8 @@ static void
 _handle_slow_timers(struct tcpcb *tp, uint32_t tick_passed)
 {
        uint32_t tt_flags = tp->m_timer.tt_flags & ((1 << TCPT_NTIMERS) - 1);
-
-       for (int i = TT_REXMT; tt_flags && i < TCPT_NTIMERS; i++ ) {
+       int i;
+       for (i = TT_REXMT; tt_flags && i < TCPT_NTIMERS; i++ ) {
                if ((tt_flags & (1 << i)) == 0)
                        continue;
                tt_flags &= ~(1 << i);

```

4) quick test with eflow wth one core should 15gbps vs 23gbps in the original version

**Comment by jsmoon** [comment]
@hhaim, thank you for your review.
1. I copied it by TCP_MAXHLEN(=60) for tcp_dooptions also.
2. I added it. But I think it has been done already in the `CFlowTable::parse_packet` with counting `m_err_len_err`.
3. I changed it as you suggested.
4. Could you share your command? I cannot make it.

**Comment by hhaim** [comment]
@jsmoon 

Almost there,

Looking more into the code and comparing it to the old stack, it shows much more logic so I understand why there is more cpu cycles now. 
The code integration is very clean, nice work!

* in reagards to   'CFlowTable:: parse_packet with counting m_err_len_err', it  checks something else. it checks aginst the ipv4.len()  and not aginst the real mbuf size and mbuf_len == ipv4.len()+tcp.headerlen()+payload. Maybe we could add this check into the parser but it is not there today 

there is a need to convert all the tabs to spaces in the new tcp stack files, let me know if you me to do this

**Comment by jsmoon** [comment]
@hhaim, yes please do it.

**Pull request closed without merging**
