### PR TITLE
Packet capture by endpoint

### PR DESCRIPTION
**Pull request by jsmoon**
Hi, this PR is the change for issue #822.

There are lots of changes but the original capture method is still functional.
This feature will be activated only by an 'endpoint' parameter in the 'capture' 'start' request.
I have met a traffic performance issue (about 2/3 degradation during capturing) with the original packet buffer.
So I introduce a new 'endpoint buffer' for bulk operation and get the performance improvement. (about 1/8 degradation during capturing with a small snaplen value)
Because the endpoint can be a file, the buffer will keep the packets in the PCAP/PCAPNG binary format.

@hhaim please check my code and give your feedback

### CODE REVIEW

**Comment by jsmoon** [comment]
@hhaim I've prepared the whole changes I've suggested.

It contains FILE and ZMQ endpoint like the followings. (changed from #822 suggestion)
image
image

This change supports PCAP and PCAPNG with minimal information.
I think we can add more information later to the PCAPNG file.
PCAP is the default. PCAPNG can be selected by adding "?pcapng" to the endpoint.

I also added the trex-console capture command parameters to use this feature.

The FILE endpoint use case:
```capture record start --tx 0 --rx 0 --endpoint file:////tmp/?pcapng --snaplen 120```
This makes /tmp/endpoint_<number> in the server host temporarily.
```capture record stop --id 1 -o xxx.pcapng```
The file will be saved to the `xxx.pcapng` file and removed from the server host.

The ZMQ endpoint use case:
```capture monitor start -o yyy.pcap```
The CaptureMonitor thread opens the ZMQ channel, receives captured packets, and writes them to `yyy.pcap`.

**Comment by egwakim** [comment]
Hi @hhaim 
Can you check the PR?

**Comment by bdollma** [comment]
Hi @egwakim , @jsmoon 
It is the holidays season in Israel, we will be back at work next week.
Thanks,

**Comment by hhaim** [comment]
@jsmoon looks good. rebased

**Pull request closed without merging**
