### PR TITLE
Enable Scapy server for ASTF

### PR DESCRIPTION
**Pull request by Rhymmor**
Hi guys!

In our app, we use Scapy server for parsing/editing PCAP files from GUI. It would be really helpful if TRex could start in ASTF mode with Scapy server.

Thank you!

### CODE REVIEW

**Comment by ybrustin** [comment]
Hi,

Is it going to be open source GUI like for stateless?

Thanks,
Yaroslav.

**Comment by Rhymmor** [comment]
Hi @ybrustin,

We'd like to be open source, but it's not only our decision to make. It is still under discussion.

**Comment by hhaim** [comment]
I suggest to have an explicit option to enable the Scapy server for ASTF -- why to pay the time to load it, if the GUI is not ready

**Comment by Rhymmor** [comment]
@hhaim, I was going to add an option, but there is already `--no-scapy-server` flag now, should I add `--scapy-server` flag in this case?

Also, we can't publish GUI, since it won't be ready without this functionality.

**Comment by hhaim** [comment]
```--scapy-server``` would be good

**Comment by ybrustin** [comment]
Hi,

You could run the Scapy server independently from TRex, for development...

Thanks,
Yaroslav

**Comment by Rhymmor** [comment]
Added `--scapy-server` flag

**Comment by hhaim** [comment]
rebased

**Pull request closed without merging**
