### PR TITLE
Align ASTF global counter clearing policy in multi-profile

### PR DESCRIPTION
**Pull request by Cyborn-Minjae-Lee**
This is PR for an issue (ASTF global counter lifetime policy #374).

Please check and feed-back.

### CODE REVIEW

**Comment by hhaim** [comment]
@Cyborn-Minjae-Lee why the accumulation is done in json layer, instead of ```CSTTCp```

Each ```TrexAstfProfile``` should include 2 set of counters 
last_diff, old and current. 

global should add the last_diff from each profile 

The json will come naturally

**Comment by Cyborn-Minjae-Lee** [comment]
I implemented 2 set of counters.
The first set is  stats of **stopped profiles** and is added each time stopped a profile in the TrexAstfProfile class.
The second is stats of **Transmitting profiles** in TrexRpcAstfCommand class.
Finally, the "get_total_counter_values" command will get the statistic plus two sets of values.

**Comment by hhaim** [comment]
@Cyborn-Minjae-Lee I still can't see how this PR solve the issue. 
Could you explain what you are doing in case a profile is stopped and removed? How the counters do not go backward? Could you write the algorithm in high level 

1. What happen in update event of global counters 
2. What happen when a profile stop
3. What happen when a profile move from stop to delete 

I just expected a different code and I don't understand how this PR solves the issue

**Comment by Cyborn-Minjae-Lee** [comment]
1.What happen in update event of global counters:
global counters are updated only rpc command "get_total_counter_values" with stopped profiles's stats(m_entry) and adding stats for Transmitting state profiles(entry).  

2.What happen when a profile stop:
Only add just before stopped profile's stats to **All of stopped profiles**'s stats

3.What happen when a profile move from stop to delete
No action.

4. traffic start(Astf(not each profile but all) state change from Loaded to Transmitting):
Clear each profiles stats and Stopped profiles's stats as well.

**Comment by hhaim** [comment]
@Cyborn-Minjae-Lee In that case when a profile is deleted the global counter will be negative compared to previous sum.

**Comment by Cyborn-Minjae-Lee** [comment]
Deleted case, there is no action due to already added to stopped stats. so, counters is not negative.
Stopped stats include for deleted profile's which passed through stop/clean-up.

-Reset commands case:  stats will be printed '0' by Client side stats reference although Server stats had counters.

**Comment by hhaim** [comment]
@Cyborn-Minjae-Lee What do you mean by added? How do you add the counters? 
Please write a pseudo code that explains how this bug is solved 

over the 3 questions above (1,2,3)

**Comment by Cyborn-Minjae-Lee** [comment]
1.  update Global counters
`542 TrexRpcCmdAstfTotalCountersValues::_run(const Json::Value &params, Json::Value &result) {
......................
558     for (auto lpstt : sttcp_tx_list) {                  **// Accumulating for STATE_TX profiles**
559         stx->**accumlate_stats**(lpstt, false, entry);    
560     }
561 
562     stx->get_profile(DEFAULT_ASTF_PROFILE_ID)->get_stt_cp()->m_dtbl.dump_values("counter vals", true    , temp);
563     for (auto i : temp.getMemberNames()) {
564         if (!temp[i].isObject()) {
565             continue;
566         }
567         if (!entry.isMember(i)) {
568             entry[i] = Json::objectValue;
569         }
570 
571         for (auto j : temp[i].getMemberNames()) {    **// Adding  STATE_TX profiles(entry) and Stopped profiles(m_entry)**
572             if (!entry[i].isMember(j)) {
573                 entry[i][j] = 0;
574             }
575             index = atoi(j.c_str());
576             if (stx->m_entry[i][j].empty()) {
577                 continue;
578             } else if (index < stx->m_flow_table_id && index != stx->m_avg_size_id && index != stx->    m_tx_ratio_id) {
579                 if (temp[i][j].isInt64()) {
580                     entry[i][j] = **entry**[i][j].asInt64() + stx->**m_entry**[i][j].asInt64();
581                 } else {
582                     entry[i][j] = **entry**[i][j].asDouble() + stx->**m_entry**[i][j].asDouble();
583                 }
584             } else if (sttcp_tx_list.empty()) {
585                 entry[i][j] = stx->m_entry[i][j];
586             }
587         }
588     }
589 
590     result["result"] = entry;
591     result["result"]["name"] = "counter vals";
592     result["result"]["epoch"] = stx->get_epoch();
593 
594     return (TREX_RPC_CMD_OK);
595 }
`
2. function name "update_stopped_stats" which is adding Stopped profiles stats only when stopped(STATE_CLEANUP).
`908 void TrexAstfPerProfile::profile_change_state(state_e new_state) {
 909     auto old_state = m_profile_state;
 910 
 911     switch ( new_state ) {
...........
 928         case STATE_TX:
 929             m_stt_cp->m_update = true;
 930             if (m_astf_obj->is_safe_update_stats()) {
 931                 m_stt_cp->update_profile_ctx();
 932             }
 933             m_active_cores = get_platform_api().get_dp_core_count();
 934             break;
 935         case STATE_CLEANUP:                                                                        
 936             m_stt_cp->Update();
 937             m_stt_cp->m_update = false;
 938             m_astf_obj->**update_stopped_stats**(m_cp_profile_id);
 939             m_active_cores = get_platform_api().get_dp_core_count();
 940             break;
 941         case STATE_DELETE:
 942             m_stt_cp->m_update = false;
 943             m_active_cores = 1;
 944             break;
 945         case AMOUNT_OF_STATES:
 946             assert(0);
 947     }

 834 void TrexAstfProfile::**update_stopped_stats**(cp_profile_id_t profile_id) {
 835     auto profile = m_profile_list[profile_id];
 836     CSTTCp* lpstt = profile->get_stt_cp();
 837     **accumlate_stats**(lpstt, true, m_entry);                                                         
 838 }

772 void TrexAstfProfile::**accumlate_stats**(CSTTCp* lpstt, bool zero_values, Json::Value &entry) {
 773     vector<string> names;
 774     uint32_t index;
 775     Json::Value temp;
 776     double total_pps, total_tx_bw;
 777 
 778     stats_names_index();
 779 
 780     if (lpstt->m_init) {
 781         temp.clear();
 782         lpstt->m_dtbl.dump_values("counter vals", zero_values, temp);
 783 
 784         /* Member : client, server */
 785         for (auto i : temp.getMemberNames()) {
 786             if (!temp[i].isObject()) {
 787                 continue;
 788             }
 789             if (!entry.isMember(i)) {
 790                 entry[i] = Json::objectValue;
 791             }
 792 
 793             /* Member : counters index */
 794             for (auto j : temp[i].getMemberNames()) {
 795                 if (!entry[i].isMember(j)) {
 796                     entry[i][j] = 0;
 797                 }
 798 
 799                 index = atoi(j.c_str());
 800                 if (index < m_flow_table_id && index != m_avg_size_id && index != m_tx_ratio_id) {
 801                     /* externation, TCP and UDP counters */
 802                     if (temp[i][j].isInt64()) {
 803                         entry[i][j] = entry[i][j].asInt64() + temp[i][j].asInt64();
 804                     } else {
 805                         entry[i][j] = entry[i][j].asDouble() + temp[i][j].asDouble();
 806                     }
 807                 } else {
 808                     /* Flow Table counters */
 809                     entry[i][j] = temp[i][j];
 810                 }
 811             }
 812             /* counters of m_avg_size and m_tx_ratio
 813              *  - m_avg_size = (m_tx_bw_l7_r+m_rx_bw_l7_r)/(8.0*(m_tx_pps_r+m_rx_pps_r))
 814              *  - m_tx_ratio = m_tx_bw_l7_r*100.0/m_tx_bw_l7_total_r */
 815             total_pps = entry[i][m_tx_pps].asDouble() + entry[i][m_rx_pps].asDouble();
 816             total_tx_bw = entry[i][m_tx_bw_tot].asDouble();
 817             entry[i][m_avg_size] = 0.0;
 818             entry[i][m_tx_ratio] = 0.0;
 819             if (total_pps > 0.0) {
 820                 entry[i][m_avg_size] = (entry[i][m_tx_bw].asDouble()+entry[i][m_rx_bw].asDouble())      /
 821                                      (8.0*total_pps);
 822             }
 823             if (total_tx_bw > 0.0) {
 824                 entry[i][m_tx_ratio] = entry[i][m_tx_bw].asDouble()*100.0 / total_tx_bw;
 825             }
 826         }
 827     }
 828 }
`


3. No action

**Comment by hhaim** [comment]
@Cyborn-Minjae-Lee I didn't ask for the code.I can look into it. 
I've asked a few lines of **pseudo** code that shows the essence. 

* I don't like the fact that you are adding counters using json. we should change this to work with native counter

**Comment by Cyborn-Minjae-Lee** [comment]
My misunderstanding,

Actually, I thought implementation with native counters in CSTTCp . For this,
I needed to create the new function of accumulation which is complicate in hierarchy, Also needed new two instance of CSTTCp. The first is for Stopped profiles counters and the other is for Global counters.
I wondered where to locate the counters and the new function in the hierarchy of the existing CSTTCp.

**Pull request closed without merging**
