### PR TITLE
Improve tcp reass

### PR DESCRIPTION
**Pull request by jsmoon**
Hi, this PR is the change for issue #813.

It is improved by using std::map.
I added the simple histogram statistics for the maximum queue size.

@hhaim, please check my changes and give your feedback.

### CODE REVIEW

**Comment by hhaim** [comment]
@jsmoon did you try this on the original example you provided? did it improve the performance?

**Comment by jsmoon** [comment]
@hhaim, regarding performance, I didn't check it.
I had been focused on feature improvement.

**Comment by hhaim** [comment]
@jsmoon I mean this example (one flow with many drops)
https://github.com/cisco-system-traffic-generator/trex-core/issues/813

**Comment by jsmoon** [comment]
@hhaim I've checked this change is working for the example by a simple simulation program.
It was similar to the unit test.

**Comment by hhaim** [comment]
@jsmoon so to make sure I understand. in case of #813 example, after this fix the issue was solved and the DUT just happen to create many out of order that the bigger queue size (100) solves (without the need to transmission or at least very few one) ? 
There could be another option that there were a real drop in the window that this bigger queue only **mitigate** by saving the holes

**Comment by jsmoon** [comment]
@hhaim, my user did not test with this yet.
With this fix, I expect that I can distinguish the packet drops from out of ordered packets.
I'll share the result after the test is done.

**Pull request merged**
