### PR TITLE
remove STLFlowLatencyStats seq difference limit value 100000

### PR DESCRIPTION
**Pull request by jsmoon**
Hi, this PR will remove the limit(100000) of the sequence difference.

Currently, if received pkt_seq difference from exp_seq is over 100000, the latency stats will increase dropped counter even though all the packets are received successfully.
So, I'd like to remove the limitation and the maximum supported difference value will be INT32_MAX in nature.

In addition, to pass the test of test_python_tabs, I removed a tab and some trailing spaces from trex_emu_profile.py

### CODE REVIEW

**Comment by jsmoon** [comment]
@hhaim Please check my changes and give your feedback.

**Comment by hhaim** [comment]
@jsmoon what is the use-case for this? in other words, in which scenario you should have such a big dog in sac number?

**Comment by jsmoon** [comment]
My user used some value lists for thousand IPs and ports in a stream. SUT handles burst packets per flow. So there are a bunch of ooo packets and the sequence number difference is easily over the limit 100000.

**Comment by hhaim** [comment]
@jsmoon why you changed EMU profile python file? It does not seem to be relevant to this commit.

**Comment by jsmoon** [comment]
@hhaim When I performed `run-regression --func`, its result was failed. So I worried about failing when I raised this PR.
Now I can see master already fixed the file. I'll remove it and update this PR again by force.

**Comment by hhaim** [comment]
@jsmoon looks good

**Comment by jsmoon** [comment]
@hhaim I think the failure is not related to my change. Should I trigger the test again?

**Comment by jsmoon** [comment]
@hhaim Would you mind if I ask when you can process my PRs?

**Comment by hhaim** [comment]
@jsmoon working on it. back from holiday

**Comment by hhaim** [comment]
rebased.

**Pull request closed without merging**
