### PR TITLE
TRex stateful interpretting latency/jitter output

### PR DESCRIPTION
**Pull request by mcallaghan-sandvine**
1. remove duplicate/incomplete latency output interpretation that was in doc/trex_book.asciidoc
 2. various cross-refs added for doc/trex_book.asciidoc into the latency/jitter section
 3. merged and improved the latency/jitter section in doc/trex_book_basic.asciidoc
----
Signed-off-by: Matt Callaghan <mcallaghan@sandvine.com>

### CODE REVIEW

**Comment by hhaim** [comment]
very  nice!  :+1:

**Comment by hhaim** [comment]
It does not compile. 

[218/230] Processing trex_faq.html: trex_faq.asciidoc waf.css -> build/trex_faq.html
a2x: WARNING: --destination-dir option is only applicable to HTML based outputs
a2x: WARNING: --destination-dir option is only applicable to HTML based outputs
asciidoc: WARNING: trex_book.asciidoc: line 804: callout refers to non-existent list item 2
asciidoc: WARNING: trex_book.asciidoc: line 804: callout refers to non-existent list item 3
asciidoc: WARNING: trex_book.asciidoc: line 804: callout refers to non-existent list item 4
asciidoc: WARNING: trex_book.asciidoc: line 804: callout refers to non-existent list item 5
asciidoc: WARNING: trex_book.asciidoc: line 804: callout refers to non-existent list item 6
asciidoc: WARNING: trex_book.asciidoc: line 804: callout refers to non-existent list item 7
asciidoc: WARNING: trex_book.asciidoc: line 804: callout refers to non-existent list item 8
asciidoc: WARNING: trex_book.asciidoc: line 804: callout refers to non-existent list item 9
asciidoc: WARNING: trex_book.asciidoc: line 804: callout refers to non-existent list item 10
asciidoc: WARNING: trex_book.asciidoc: line 804: callout refers to non-existent list item 11
asciidoc: WARNING: trex_book.asciidoc: line 810: list item index: expected 1 got 2
asciidoc: WARNING: trex_book.asciidoc: line 810: no callouts refer to list item 1
asciidoc: WARNING: trex_book.asciidoc: line 811: list item index: expected 2 got 3
asciidoc: WARNING: trex_book.asciidoc: line 811: no callouts refer to list item 2
asciidoc: WARNING: trex_book.asciidoc: line 812: list item index: expected 3 got 4
asciidoc: WARNING: trex_book.asciidoc: line 812: no callouts refer to list item 3
asciidoc: WARNING: trex_book.asciidoc: line 813: list item index: expected 4 got 5
asciidoc: WARNING: trex_book.asciidoc: line 813: no callouts refer to list item 4
asciidoc: WARNING: trex_book.asciidoc: line 814: list item index: expected 5 got 6
asciidoc: WARNING: trex_book.asciidoc: line 814: no callouts refer to list item 5
asciidoc: WARNING: trex_book.asciidoc: line 815: list item index: expected 6 got 7
asciidoc: WARNING: trex_book.asciidoc: line 815: no callouts refer to list item 6
asciidoc: WARNING: trex_book.asciidoc: line 816: list item index: expected 7 got 8
asciidoc: WARNING: trex_book.asciidoc: line 816: no callouts refer to list item 7
asciidoc: WARNING: trex_book.asciidoc: line 817: list item index: expected 8 got 9
asciidoc: WARNING: trex_book.asciidoc: line 817: no callouts refer to list item 8
asciidoc: WARNING: trex_book.asciidoc: line 818: list item index: expected 9 got 10
asciidoc: WARNING: trex_book.asciidoc: line 818: no callouts refer to list item 9
asciidoc: WARNING: trex_book.asciidoc: line 819: list item index: expected 10 got 11
asciidoc: WARNING: trex_book.asciidoc: line 819: no callouts refer to list item 10
asciidoc: ERROR: trex_book_basic.asciidoc: line 3290: illegal style name: source%nowrap
a2x: ERROR: "/usr/bin/asciidoc" --backend docbook -a "a2x-format=pdf"  --doctype book  --out-file "/auto/srg-sce-swinfra-usr/emb/users/hhaim/work/depot/asr1k/emb/privhhaim/bp_sim_git/trex-core/doc/build/trex_book.xml" "/auto/srg-sce-swinfra-usr/emb/users/hhaim/work/depot/asr1k/emb/private/hhaim/bp_sim_git/trex-core/doc/trex_book.a

**Comment by mcallaghan-sandvine** [comment]
@hhaim , FYI http://asciidoctor.org/docs/user-manual/#to-wrap-or-to-scroll
(asciidoc should have supported that ... but no worries, just removing it)

**Comment by mcallaghan-sandvine** [comment]
All fixed;  Should I re-squash?

**Comment by mcallaghan-sandvine** [comment]
(screwed up the squash ugh)

**Comment by mcallaghan-sandvine** [comment]
replaced by: https://github.com/cisco-system-traffic-generator/trex-core/pull/101

**Pull request closed without merging**
