### PR TITLE
Add support for latency HDR histograms

### PR DESCRIPTION
**Pull request by ahothan**
- Added new src/hdrh directory containing a copy of the HDR Histogram library (C, C++) https://github.com/HdrHistogram/HdrHistogram_c
- Added --hdrh option to trex main to enable latency collection and reporting with HDR histograms
- Updated python library to insert hdr strings in the returned dict

Have not modified any doc to describe the feature...

### CODE REVIEW

**Comment by hhaim** [comment]
Looks good. I would be better to add a RPC configuration to enable/disable it (instead of CLI)
Will verify it in our regression

**Comment by hhaim** [comment]
It has a build failure

```
 4/324] Compiling ../src/gtest/bp_tcp_gtest.cpp
[ 5/324] Compiling ../src/gtest/bp_astf_interactive_gtest.cpp
In file included from ../../src/rx_check.h:27:0,
from ../../src/bp_sim.h:50,
from ../../src/main.cpp:23:
../../src/time_histogram.h:33:27: fatal error: hdr_histogram.h: No such file or directory
compilation terminated.

In file included from ../../src/rx_check.h:27:0,
from ../../src/bp_sim.h:50,
from ../../src/bp_gtest.cpp:22:
../../src/time_histogram.h:33:27: fatal error: hdr_histogram.h: No such file or directory
compilation terminated.

In file included from ../../src/rx_check.h:27:0,
from ../../src/bp_sim.h:50,
from ../../src/sim/trex_sim.h:26,
from ../../src/bp_gtest.h:19,
from ../../src/gtest/bp_astf_interactive_gtest.cpp:25:
../../src/time_histogram.h:33:27: fatal error: hdr_histogram.h: No such file or directory
compilation terminated.

Waf: Leaving directory `/tmp/build_4499_trex_283af06628eb4f672b022e785870bd38a8dfe818/linux/build'

```

**Comment by ahothan** [comment]
that's odd because it builds for me... DId you start fron scratch with a ./b configure?
I did add a new include path in ws_main.py:
includes_path = '''
                   ../src/
                   ../src/drivers/
                   ../src/pal/common/
                   ../src/pal/linux_dpdk/
                   ../src/stx/
                   ../src/stx/common/
                   ../src/utils/
                   ../src/hdrh/

**Comment by ybrustin** [comment]
@ahothan 
It's about linux/ws_main.py
You have changed only linux_dpdk/ws_main.py

**Comment by ahothan** [comment]
ah ok I missed that build completely!
I have patched that ws_main.py and to my surprise, the build throws several errors related to void* implicit cast not allowed (-fpermissive):

../../src/hdrh/hdr_histogram_log.c: In function ‘int hdr_log_decode(hdr_histogram**, char*, size_t)’:
../../src/hdrh/hdr_histogram_log.c:1193:65: error: invalid conversion from ‘void*’ to ‘uint8_t* {aka unsigned char*}’ [-fpermissive]
     compressed_histogram = malloc(sizeof(uint8_t)*compressed_len);

 Why is it that it finds errors in ./linux but not in ./linux_dpdk?
Do you use different flags or only consider warnings as error in ./linux build?
I'll work on fixing the errors but would like to understand why errors are not found on the linux_dpdk build.

**Comment by ahothan** [comment]
Just committed the changes to linux build directory + fixes to the warning, please check again

**Comment by hhaim** [comment]
In one of the platform, there is a link failure. is clock_gettime needed ?

```[331/332] Linking build/linux/bp-sim-64-debug
src/hdrh/hdr_time.c.1.o: In function `hdr_gettime':
/tmp/build_4501_trex_ba1e6cff6425a37c072e47d40a75f3a2416b01f5/linux/build/../../src/hdrh/hdr_time.c:68: undefined reference to `clock_gettime'
src/hdrh/hdr_time.c.1.o: In function `hdr_getnow':
/tmp/build_4501_trex_ba1e6cff6425a37c072e47d40a75f3a2416b01f5/linux/build/../../src/hdrh/hdr_time.c:73: undefined reference to `clock_gettime'
collect2: error: ld returned 1 exit status
```

**Comment by ahothan** [comment]
ok - let me see how to get rid of it and I'll update the PR

**Comment by ahothan** [comment]
I have compiled out that code which is actually unused in this context (only needed for hdrhc unit test code which we do not include)

**Comment by ahothan** [comment]
the hdrhc team has come back with this suggestion:
	I'll see if there is a way to fall back, e.g does the platform without clock_gettime have gettimeofday?

if we can avoid modifying that code and use a compile flag instead, that will prevent us from having a diverging copy of hdrhc code in trex tree

**Comment by ahothan** [comment]
Also I'm not sure how this PR would work out once merged, I hope it will squash all commits in my branch into 1?

**Comment by hhaim** [comment]
Yes, I’m usually rebasing it

**Comment by hhaim** [comment]
Regression does not work. 
have a look how to run it here 

https://github.com/cisco-system-traffic-generator/trex-core/wiki#how-to-contribute

I would start from here:
```
$cd script
$ ./run_regression --func
```


```
 Process terminating with default action of signal 11 (SIGSEGV)
==15935== Access not within mapped region at address 0x5F
==15935== at 0x4A0CB89: memset (vg_replace_strmem.c:1239)
==15935== by 0x251205: Reset (time_histogram.cpp:64)
==15935== by 0x251205: CTimeHistogram::Create() (time_histogram.cpp:76)
==15935== by 0x36E7A4: CRFC2544Info::create() (trex_latency_counters.cpp:8)
==15935== by 0x3D908F: TrexStatelessDpPerPort (trex_stl_dp_core.cpp:520)
==15935== by 0x3D908F: TrexStatelessDpCore::TrexStatelessDpCore(unsigned char, CFlowGenListPerThread*) (trex_stl_dp_core.cpp:927)
==15935== by 0x3B8E93: TrexStateless::create_dp_core(unsigned int, CFlowGenListPerThread*) (trex_stl.cpp:251)
==15935== by 0x21E20B: CFlowGenListPerThread::Create(unsigned int, CFlowGenList*, unsigned int) (bp_sim.cpp:2870)
==15935== by 0x21E6A9: CFlowGenList::generate_p_thread_info(unsigned int) (bp_sim.cpp:4277)
==15935== by 0x1DA701: CBasicStl::init() (trex_stateless_gtest.cpp:2698)
==15935== by 0x1B91CA: basic_stl_pcap_remote_dual_Test::TestBody() (trex_stateless_gtest.cpp:4792)
==15935== by 0x2E15DD: testing::Test::Run() [clone .part.372] (gtest-all.cc:3452)
==15935== by 0x2E4E2C: Run (gtest-all.cc:3410)
==15935== by 0x2E4E2C: testing::internal::TestInfoImpl::Run() [clone .part.374] (gtest-all.cc:3671)
==15935== by 0x2E5004: Run (gtest.h:16302)
==15935== by 0x2E5004: testing::TestCase::Run() [clone .part.375] (gtest-all.cc:3777)
==15935== If you believe this happened as a result of a stack
==15935== overflow in your program's main thread (unlikely but
==15935== possible), you can try to increase the size of the
==15935== main thread stack using the --main-stacksize= flag.
==15935== The main thread stack size used in this run was 8388608.
==15935== 
```

**Comment by hhaim** [comment]
This fix the crash, 
https://github.com/hhaim/trex-core/commit/c74cb50f6129a73ddafbeda9813ae77300af7f5e

could you review?

**Comment by hhaim** [comment]
Thanks Alec, rebased.

**Pull request closed without merging**
